### ISSUE TITLE
Bind selectors to class instances?

### ISSUE THREAD

**Issue by wmertens** [reduxjs/reselect#232]
In #231 I describe how I use selectors to derive data from props and state. It would be nice if that could be expressed more elegantly.

For example, suppose you can do:
```js
class Thing extends React.Component  {
  state = {show: false}
  items = createBoundSelector(this, ["state.show", "props.data"], deriveItemsFromData)
  summary = createBoundSelector(this, "items", summaryFromItems)

  render() {
    const summary = this.summary()
    // …
  }
}
```

So basically, the inputSelectors are thunked via string paths, e.g. `"state.show"` is equivalent to `() => this.state.show`.

Another approach might be to add getters to the instance in the constructor, e.g.
```js
class Thing extends React.Component  {
  constructor(props) {
    super(props)
    this.state = {show: false}
    addGetter(this, 'items', ["state.show", "props.data"], deriveItemsFromData)
    addGetter(this, 'summary', "items", summaryFromItems)
  }
  render() {
    const {summary} = this
    // …
  }
}
```
although I'm not sure how that works across browsers.

I suppose that instead of `createBoundSelector(this, paths, fn)` one could write `createSelector(boundSelectors(this, paths), fn)`, in which case `boundSelectors` may or may not be an addition for this library.

Basically, opening this issue for discussing the best approach.

**Comment by wmertens** [comment]
Maybe something that creates a class to `extend` from, so that the selectors are all prototype functions sharing their cache on the instance? That would remove the need to bind selectors at instantiation time, making the VMs happier…

**Comment by markerikson** [comment]
Closing since it's stale and class components are not sufficiently relevant today.
