### ISSUE TITLE
Using previously calculated return value even if args equality check fails

### ISSUE THREAD

**Issue by felixSchl** [reduxjs/reselect#239]
Consider searching a list. The list and the search predicate might change but the result might equal the previously calculated list. Returning the previously calculated value, if available, would gain us reference equality. For this to work, a second equality-check function would need to be provided, for example `_.eq` from lodash or something. What do you think?

**Comment by joedski** [comment]
Hello from the far future.

I think this is orthogonal to what reselect should do.  It's pretty simple to solve with a wrapper:

```js
function keepLastIfEqual(eqFn) {
  return function withKeepLastIfEqual(fn) {
    let cachedResult;

    return function $withKeepLastIfEqual(...args) {
      const nextResult = fn(...args);
      if (!eqFn(cachedResult, nextResult)) {
        cachedResult = nextResult;
      }
      return cachedResult;
    }
  }
}

const createDeepEqAwareSelector = compose(
  keepLastIfEqual(_.eq),
  createSelector
);

const selectThingsForFoo = createDeepEqAwareSelector(
  [
    selectThingsCollection,
    (state, search) => search,
  ],
  (thingsCollection, search) =>
    _.values(thingsCollection).filter(thingsForSearch(search))
);
```
