### ISSUE TITLE
Logical Operator Or in createStructuredSelector

### ISSUE THREAD

**Issue by albert-olive** [reduxjs/reselect#269]
Hi,

I know it's possible to do that in the selector but I wish to do that here:

    const mapStateToProps = createStructuredSelector({
      product: (
        getCurrentProductFromProducts() ||
        getSellingProductItemFromLastPostedOrCurrentProduct() ||
        getSoldProductItemFromLastPostedOrCurrentProduct())
    });

With this code, if the first selector is undefined or null, it does not go to the second or the third one.

**Comment by heyimalex** [comment]
You can just do this in mapStateToProps, assuming all of those are selector functions.

```js
const mapStateToProps = state => ({
  product:
    getCurrentProductFromProducts(state) ||
    getSellingProductItemFromLastPostedOrCurrentProduct(state) ||
    getSoldProductItemFromLastPostedOrCurrentProduct(state)
});
```
