### ISSUE TITLE
Document usage with `combineReducers`

### ISSUE THREAD

**Issue by udalrich** [reduxjs/reselect#306]
I have a store that is made with `combineReducers`, sometimes more than one level deep, which looks  something like

    { 
        a: ...,
        b: ...,
        c: {
             c1: ...,
             c2, ...
        }
    }

where each of the named entries is made from reducers that generally look like

    (state, action) => ({
         ...state,
         foo: action.payload
    }); 

So if I have a selector that look at `state.a.foo` or `state.c.c2.bar`, will the memorization work correctly here?  The top of the state is new objects, but those hold old objects.  Since I am creating new objects, I was initially concerned that this would result in frequent recalculations, even when the state did not change.  Thinking about it some, I am pretty sure that what happens in the equality check is the selected parts of the state are compared, so if one `state.a.quz` changed, then the above selector would not run. 

Since this is (I think) a common style, it would be useful to include an explicit mention of it as a technique that does (or does not) work.

**Comment by markerikson** [comment]
I don't think `combineReducers` is relevant to use of selectors, really.  It's just a question of whether _all_ parameters to the selector function are `===` to the last time it was called, or not.
