### ISSUE TITLE
Disable reselect method caching in dev mode?

### ISSUE THREAD

**Issue by smonev** [reduxjs/reselect#309]
Hello, while developing I would like to disable reselect and just hit the regular non cached method. Is this possible?

**Comment by AlexGalays** [comment]
This is best done in user land; Something like :

// utils/createSelector.js
```js
import { createSelector as defaultCreateSelector, createSelectorCreator } from 'reselect'

export const createSelector = process.env.NODE_ENV === 'production'
  ? defaultCreateSelector
  : createSelectorCreator(func => func)
```

and always use that local version.

Didn't test that code but you get the idea :)

**Comment by smonev** [comment]
Thanks @AlexGalays, worked great. Not sure why this is not the default behavior though.
