### ISSUE TITLE
How to use reselect with stateless functions

### ISSUE THREAD

**Issue by vinodkolla** [reduxjs/reselect#328]
I am trying to use reselect outside the component. I have a bunch of selectors created that can be called from anywhere of the project. Here is the example of my selectors:
`const selectFoo = () => getStore().getState().foo;`
`export const getFooBar = createSelector(selectFoo, foo => foo.bar);`
when I make a call to 'getFooBar' it is not getting the value form the updated store. So, I have to pass the state as arguments for every selector call I make. Is it possible to make a call to get selectors without passing state and still get the updated state?

**Comment by markerikson** [comment]
Selectors by definition are supposed to receive the current state as an argument.
