### ISSUE TITLE
Suggestion: isSelector function

### ISSUE THREAD

**Issue by timhwang21** [reduxjs/reselect#333]
Hi, wondering if you think this would be a useful feature. Sometimes we're interested in enforcing that something is a selector (in tests, proptype validations etc.). We're currently doing something like `isSelector = f => !!f.resultFunc`. Pretty trivial but may be useful to some people. I can open a PR if this is useful; if not that's fine. Thanks!

**Comment by markerikson** [comment]
Closing since this is stale.  If someone still feels this would be useful, open a PR and we can discuss.
