### ISSUE TITLE
Memoized selector for retrieval by ID

### ISSUE THREAD

**Issue by xehpuk** [reduxjs/reselect#335]
Super easy question.

I have a state like this:
```js
state = {
  todos: [{
    id: 1,
    text: 'Ask reselect question.'
  }]
}
```

How can I write a memoized selector `getTodoById(state, id)` so that `state.todos.find(...)` is only called if `state.todos` or `id` changes?

**Comment by markerikson** [comment]
See my post [Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance](http://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/), particularly the last section on using the "factory function" form of `mapState`.
