### ISSUE TITLE
pagination?

### ISSUE THREAD

**Issue by Bonobomagno** [reduxjs/reselect#337]
any tip about the pagination?
how to handle that? Double selector or any api for that?
The main goal is to paginate the reselect output, without recompute it.

**Comment by toomuchdesign** [comment]
Hi @Bonobomagno, probably [reselect's stackoverflow page](https://stackoverflow.com/questions/tagged/reselect) is the best place to ask for some advice. 😄 

BTW, [this paragraph](https://github.com/toomuchdesign/re-reselect#other-viable-solutions) from `re-reselect` docs could give you some hints.
