### ISSUE TITLE
Memoization unit tests fail expectations

### ISSUE THREAD

**Issue by im1dermike** [reduxjs/reselect#344]
I've created the following tests to verify my selector which takes a dynamic parameter:

```
export interface TestState {
  fields: Field[];
  num: number;
}

describe('selector', () => {
  it('should memoize field calls', () => {
    let state: TestState = {
      fields: [
        { dataType: DataType.Numeric, name: "Numeric1" },
        { dataType: DataType.Numeric, name: "Numeric2" },
        { dataType: DataType.String, name: "String1" },
        { dataType: DataType.String, name: "String2" },
        { dataType: DataType.String, name: "String3" },
        { dataType: DataType.Boolean, name: "Boolean1" },
        { dataType: DataType.Boolean, name: "Boolean2" },
        { dataType: DataType.Boolean, name: "Boolean3" },
        { dataType: DataType.Boolean, name: "Boolean4" },
      ],
      num: 0
    };

    const selector = createSelector(
      (state: TestState) => state.fields,
      (state) => memoize(
        (dataType: DataType) => {
          return state.filter(field => field.dataType === dataType)
        }
      )
    );

    const fieldsFilter = selector(state);

    // fetching string fields
    expect(fieldsFilter(DataType.String).length).toEqual(3);
    expect(selector.recomputations()).toEqual(1);
    
    // re-fetching string fields; checking fields selector not recomputed
    expect(fieldsFilter(DataType.String).length).toEqual(3);
    expect(selector.recomputations()).toEqual(1);
    
    // re-fetching numeric fields; checking fields selector IS recomputed
    expect(fieldsFilter(DataType.Numeric).length).toEqual(2);
    expect(selector.recomputations()).toEqual(2);
  });
});
```

My expectation is that the first time the selector fires (for `DataType.String`) it computes the result.  When the selector is called again for `DataType.String`, it does not recompute.  But when the selector is called a third time for `DataType.Numeric`, it will recompute the result for the second time.

In my tests, however, `selector.recomputations()` is always 1.  What am I not understanding?

**Comment by markerikson** [comment]
I'm kind of confused by what you're doing.  Your "output selector" (the last arg to `createSelector()`) appears to be returning its own memoized function.  That output selector will only re-run when you call `selector(someValue)`, and pass in a different value.  You're only calling `selector(state)` once, therefore the the selector only recomputes once.  The fact that you're returning a function and calling it multiple times has nothing to do with the original selector re-running and potentially recomputing.

**Comment by im1dermike** [comment]
My selector is based off the one example for a selector with a dynamic argument in the reselect documentation:

```
const expensiveSelector = createSelector(
  state => state.items,
  items => memoize(
    minValue => items.filter(item => item.value > minValue)
  )
);
const expensiveFilter = expensiveSelector(state);
const slightlyExpensive = expensiveFilter(100);
```

If I change my code to call `selector(state)` each time, it still returns 1 for all tests.

```
  // fetching string fields
  let fieldsFilter = selector(state);
  expect(fieldsFilter(DataType.String).length).toEqual(3);
  expect(selector.recomputations()).toEqual(1);
  
  // re-fetching string fields; checking fields selector not recomputed
  fieldsFilter = selector(state);
  expect(fieldsFilter(DataType.String).length).toEqual(3);
  expect(selector.recomputations()).toEqual(1);
  
  // re-fetching numeric fields; checking fields selector IS recomputed
  fieldsFilter = selector(state);
  expect(fieldsFilter(DataType.Numeric).length).toEqual(2);
  expect(selector.recomputations()).toEqual(2);
```

**Comment by markerikson** [comment]
Yes.  A Reselect selector only recomputes when the _values returned from the input selectors change_.  You're always calling `selector()` with the same `state` argument, and the one input selector is always returning `state.items`, so it's returning the same value every time.

You might want to read my post [Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance](http://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/) to get a better understanding of how selectors work and how to use them.

**Comment by im1dermike** [comment]
> You're always calling selector() with the same state argument, and the one input selector is always returning state.items, so it's returning the same value every time. To force a recomputation, you'd need to call selector() with a state object that has a different state.items reference.

What is potentially changing in my situation is the dynamic argument.  Given the dynamic example above, pulled from reselect's documentation, the same thing is happening:

```
const expensiveFilter = expensiveSelector(state);
const slightlyExpensive = expensiveFilter(100);
const veryExpensive = expensiveFilter(1000000)
```

The only thing changing between `slightlyExpensive` and `veryExpensive` is the dynamic argument.  Are you saying it will return the same value every time in this example too?

**Comment by markerikson** [comment]
I'm saying you're not calling the _selector_ multiple times with different arguments.  You're calling _the function you're returning from the selector_ multiple times.

In other words, the Reselect recomputation is only when you call `expensiveSelector(value1)` and `expensiveSelector(value2)`.  The fact that you're returning another memoized function you created yourself, and then calling it multiple times, has nothing to do with the selector you created using `createSelector()`.

**Comment by im1dermike** [comment]
```

describe('selector', () => {
  it('should memoize field calls', () => {
    let state: TestState = {
      taxAssistFields: [
        { dataType: DataType.Numeric, fieldName: "Numeric1", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.Numeric, fieldName: "Numeric2", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.String, fieldName: "String1", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.String, fieldName: "String2", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.String, fieldName: "String3", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.Boolean, fieldName: "Boolean1", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.Boolean, fieldName: "Boolean2", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.Boolean, fieldName: "Boolean3", fieldOption: [], readOnlyIndicator: false },
        { dataType: DataType.Boolean, fieldName: "Boolean4", fieldOption: [], readOnlyIndicator: false },
      ],
      num: 0
    };

    const reducer = (state: TestState, action?: any) => (
      {
        taxAssistFields: state.taxAssistFields,
        num: action ? action(state.num) : state.num
      }
    );

    const selector = createSelector(
      (state: TestState) => state.taxAssistFields,
      (state: TestState) => state.num,
      (state, num) => memoize(
        (dataType: DataType) => {
          return state.filter(field => field.dataType === dataType && num === 0)
        }
      )
    );

    // fetching string fields
    let fieldsFilter = selector(state);
    expect(fieldsFilter(DataType.String).length).toEqual(3);
    expect(selector.recomputations()).toEqual(1);
    
    // re-fetching string fields; checking fields selector not recomputed
    fieldsFilter = selector(state);
    expect(fieldsFilter(DataType.String).length).toEqual(3);
    expect(selector.recomputations()).toEqual(1);
    
    // incrementing num; checking fields selector recomputed
    expect(state.num).toEqual(0);
    state = reducer(state, (x: any) => x + 1);
    expect(state.num).toEqual(1);    
    expect(selector.recomputations()).toEqual(2);
  });
});
```

If that's the case, shouldn't this example recompute a second time for the last test since one of the input selectors has changed?  Because it equals 1 not 2.

**Comment by markerikson** [comment]
I don't see you calling `selector(newState)` anywhere in that last sequence, so no, it won't have recomputed.

(Also, passing functions inside of an action is generally considered a bad practice, and we advise against it.  See the [Redux FAQ entry on serializable actions](https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants).)

**Comment by im1dermike** [comment]
https://github.com/reduxjs/reselect#q-how-do-i-test-a-selector
