### ISSUE TITLE
Documentation on composing selectors with immutableJS

### ISSUE THREAD

**Issue by cal0610** [reduxjs/reselect#345]
Documentation now:

```
const taxSelector = createSelector(
  subtotalSelector,
  taxPercentSelector,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)
```

Documentation for immutable js:

```
const taxSelector = createSelector(
  subtotalSelector(),
  taxPercentSelector(),
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)
```

Been through the docs and couldn't find any info on this, please let me know if I missed it. Cheers

**Comment by sunndeath** [comment]
> Documentation now:
> 
> ```
> const taxSelector = createSelector(
>   subtotalSelector,
>   taxPercentSelector,
>   (subtotal, taxPercent) => subtotal * (taxPercent / 100)
> )
> ```
> 
> Documentation for immutable js:
> 
> ```
> const taxSelector = createSelector(
>   subtotalSelector(),
>   taxPercentSelector(),
>   (subtotal, taxPercent) => subtotal * (taxPercent / 100)
> )
> ```
> 
> Been through the docs and couldn't find any info on this, please let me know if I missed it. Cheers

You should use "immitable-way" syntax inside the selector ([obj, innerField, ...]), like that: https://medium.com/@tylorshin/using-reselect-with-immutablejs-772793913a9d

**Comment by markerikson** [comment]
FWIW, we now specifically recommend that you _not_ use Immutable.js with Redux:

https://redux.js.org/style-guide/style-guide#use-plain-javascript-objects-for-state
