### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by ellbee** [reduxjs/reselect#351]
As we have some changes to the TypeScript typings and I am nervous to release them in a minor release (as they have broken peoples builds in the past), I am planning to release version 4.

Currently planned features:

- Updated TypeScript typings (#274, #315)
- Exposed selector dependencies (#251)
- Use provided memoize function for selectors (#297)

Help wanted:
- Can we solve #340 for this release?

**Comment by wmertens** [comment]
How about adding a `createNonPureSelector`? https://github.com/reduxjs/reselect/issues/231#issuecomment-291155643

**Comment by MaxZhuravsky** [comment]
Maybe add createAsyncSelector #142 ?

**Comment by skortchmark9** [comment]
Any progress on releasing this? I'm pretty excited

**Comment by ellbee** [comment]
I have released 4.0.0-beta.1 to npm which addresses:

- Updated TypeScript typings (#274, #315)
- Exposed selector dependencies (#251)
- Use provided memoize function for selectors (#297)

**Comment by skortchmark9** [comment]
Ah yeah, I noticed that - but it was 2 months ago! What are the conditions for releasing the actual 4.0.0?

**Comment by ellbee** [comment]
Let's have one last go at solving #340 and if we don't come up with anything satisfactory in the next week or so go ahead and release. How do people feel about the suggestion in #366 to only have the typings cover the array of input selectors?

**Comment by markerikson** [comment]
@ellbee : my big concern with switching the order of input vs output selectors is that it's a _huge_ breaking change for Reselect.  I'm not entirely against it, but there's going to be a lot of people out there who do `yarn add reselect` and suddenly it doesn't work the way they expect.

**Comment by jimbol** [comment]
Ready for the update :)

**Comment by ellbee** [comment]
Released!

If a solution for #340 is agreed upon we'll release it in a version 5.

**Comment by nickmccurdy** [comment]
Reselect 4.0.0 is out, it seems like this can be closed.
