### ISSUE TITLE
Possible to use with @connect

### ISSUE THREAD

**Issue by john-wealthmigrate** [reduxjs/reselect#354]
Hi,

I created a selector similarly to the following (pseudo example only)

```
const alertItemsSelector = state => state.alerts.items

const visibleAlertsSelector = createSelector(
  alertItemsSelector,
  items => items
)
```

Then I try to use this in my @connect decorator

```
@connect((state) => { 
  return {
    alerts: visibleAlertsSelector(state)
  };
})
Something extends Component

```
However when I try to access alerts in my component I just get back a function() ?

I didn't see any clear documentation about using the @connect decorator and I assume it would work the same as mapStateToProps am I missing something?

**Comment by markerikson** [comment]
@john-wealthmigrate : `connect` isn't actually a decorator - it's just a function.  If you have decorators enabled in your build setup, you can use it as a decorator, but we generally discourage that.

Having said that, the code you're showing looks mostly valid, although your `visibleAlertsSelector` is rather pointless - it'll always return the same value as `alertItemsSelector`, and there's no memoization involved.
