### ISSUE TITLE
Suggestion: Usage examples should use `selectTheThing` naming pattern instead of `getTheThing`

### ISSUE THREAD

**Issue by samdesota** [reduxjs/reselect#355]
One thing I've found to be very helpful when working with reselect has been naming selectors with `selectTheThing` instead of `getTheThing`.

`get` is a overloaded term in programming. I've found that when I use `get` for my selectors very often the conflict with other types of getters. This is especially impactful when using selectors with auto-imports. 

Obviously, users are free to call selectors whatever they want, but I've found that when telling people about the `select__` pattern they tend to facepalm and wish the documentation used that pattern when they learned reselect.

**Comment by zomars** [comment]
I agree with this, get sometimes implies a fetch call.

**Comment by markerikson** [comment]
Agreed, we should update examples this way.
