### ISSUE TITLE
Thoughts on using libraries within selectors, returning functions, etc

### ISSUE THREAD

**Issue by TENsaga** [reduxjs/reselect#356]
Hey folks, tried to find an answer online but haven't seen much on this subject: Is there anything wrong with using libraries to work with data inside selectors? We have a few selectors that are used throughout an application, the selector results are also used to speed up filtering options:

```
// Virtualized Select Options
export const getAOptions = createSelector(getA, aResults =>
    aResults.map(a => ({
        key: a.id,
        label: a.a,
        value: a.a,
    })));

// Virtualized Select Fast Filter
export const getAFastFilter = createSelector(getAOptions, aFilter =>
    createFilterOptions({ options: aFilter }));
```

The component uses the results from getAOptions and getAFastFilter.  getAFastFilter returns the library function, the results from createFilterOptions are in an array.

Thanks for the support.

**Comment by joedski** [comment]
I've somewhat frequently used selectors to return functions, usually to allow getting of dependencies for derived entities without having to pass the whole state into the selector's computation function.  So long as you know what it is you're actually trying to cache, it should be fine.  I realize that doesn't say anything specific about your case, but I think it applies to what you're asking.

**Comment by TENsaga** [comment]
Yeah thanks, your point of view is definitely helpful. 

We modified it slightly and are now calling createFilterOptions immediately inside createSelector, the results and PropType validation is the array of results:

```
// Virtualized Select Fast Filter
export const getAFastFilter = createSelector(getAOptions, aFilter =>
    createFilterOptions({ options: aFilter })**()**);
```

In my head it should still be caching and bypassing having to rerun it each time, but if anyone can correct me on this let me know.

**Comment by joedski** [comment]
Should work.  It should only invalidate the cache if the result returned by `getAOptions` itself changes.
