### ISSUE TITLE
Only using memoized input when it's been modified

### ISSUE THREAD

**Issue by Fandekasp** [reduxjs/reselect#361]
Not sure how to explain this, so an example should be clearer:

selectors/errors.js
```es6
import {createSelectorWithDependencies as createSelector} from "reselect-tools";
import {findLastError} from "~/filters";

const selectFirebaseError = createSelector(
  state => state.firebase.errors,
  findLastError,
);

const selectUiError = createSelector(state => state.ui.errors, findLastError);

export const selectCurrentError = createSelector(
  selectFirebaseError,
  selectUiError,
  (firebaseError, uiError) => {
    // I only want to return any new error
  },
);
```

filters/errors.js
```es6
export const findLastError = errors => {
  const [error] = errors ? errors.slice(-1) : [null];
  const code = _.get(error, "code");
  const message = _.get(ERRORS, code) || ERRORS["unknown-error"];
  const duration = _.get(error, "duration", 3000);

  return {message, duration};
};
```

components/Snackbar.js
```es6
import React, {Component} from "react";
import PropTypes from "prop-types";
import {connect} from "react-redux";
import MUSnackbar from "material-ui/Snackbar";
import {selectCurrentError} from "~/selectors";

@connect(selectCurrentError)
export default class Snackbar extends Component {
  static propTypes = {
    error: PropTypes.shape({
      message: PropTypes.string.isRequired,
      duration: PropTypes.number.isRequired,
    }),
  };

  render() {
    const {error} = this.props;

    return error ? (
      <MUSnackbar
        open={!_.isEmpty(error.message)}
        message={error.message}
        autoHideDuration={error.duration}
      />
    ) : null;
  }
}
```

Both the `state.firebase.errors` and `state.ui.errors` are lists of errors, and I want to display the last error from any of them in my snackbar. I'm confused as to how I could proceed here. How can I detect the most recently modified selector here ?

**Comment by joedski** [comment]
If `state.firebase.errors` and `state.ui.errors` are independent lists, then you have no information to determine which last error was more recent than the other.  That's additional information you have to track somewhere.

Some ideas for how this might be tracked:
- Add timestamps to each error and take which ever one has the most recent timestamp.
- Track the combined order of all errors across all lists in a separate list in the state.  This can be eased by giving each error a unique id.
- Keep all errors in a single list, and distinguish them using an additional "source" prop, where `error.source = 'firebase' or 'ui' or ... something else`.

I'm partial to the last one, personally.

**Comment by Fandekasp** [comment]
I gave up on trying to centralize errors, and throw snackbar messages with the js-snackbar library directly from components, actions & sagas.

Thanks for you insight!
