### ISSUE TITLE
Sharing Selectors with Props Across Multiple Component Instances and Out of the lifecycle

### ISSUE THREAD

**Issue by enmanuelduran** [reduxjs/reselect#365]
When sharing selectors across multiple instances we create a private copy of the selector for each instance, it works prefectly but it got me thinking about one thing, what if we want to memoize the selector even if the user _unmounted_ the component and came back to it immediatly _without_ mutating the selected state and props? could it reuse the last memoized result still?

In the documentation we have this example:
```
const makeMapStateToProps = () => {
  const getVisibleTodos = makeGetVisibleTodos()
  const mapStateToProps = (state, props) => {
    return {
      todos: getVisibleTodos(state, props)
    }
  }
  return mapStateToProps
}`
```

`getVisibleTodos` is defined inside the `makeMapStateToProps` which means that  the selector is memoized as long as the component is not _unmounted_, when it gets unmounted the memoization is cleaned up which means that if we come back it will compute again.

but, what if we do something like:

```
const getVisibleTodos = makeGetVisibleTodos() // We take it out of the cycle
const makeMapStateToProps = () => {
  const mapStateToProps = (state, props) => {
    return {
      todos: getVisibleTodos(state, props)
    }
  }
  return mapStateToProps
}`
```

`getVisibleTodos` is not part of the _lifecycle_ anymore, which means that if the component is unmounted it'll still be available if you access that component again without changing the part of the state and props we selected in the selector.

Is this a valid approach? 
if not? what are the possible drawbacks of doing this?
I've tested this hypothesis and it seems to work.

**Comment by markerikson** [comment]
@enmanuelduran : that example won't memoize correctly at all, because you're back to using a single shared copy of `getVisibleTodos` across all instances of this component, and passing in a different `props` object reference for each one.

**Comment by enmanuel-duran-olx** [comment]
@markerikson I'm testing with a component connected with redux putting the _selector creator_ out of the `makeMapStateToProps` as I mentioned in the example and it looks like it's memoizing correctly even when unmounting the component, this is what happens:

1) I Mount the component and the selector is executed once with prop "A" (I'm tracking this with a console.log inside the selector)
2) I go back to another component, come back to the same component with same prop "A" by clicking on a link and the selector is not executed again, `console.log` doesn't execute (memoizing is working, at least looks like it).
3) I go back to another component, come back to the same component with another prop "B" by clicking on a link, the `console.log` is now executed inside the selector with the new prop "B" working correctly.

any ideas of why this could be happening? I don't mean to bother, I just want to understand why this is happening, I'm looking at the function `defaultMemoize` in the source code of reselect and added a `console.log` in the `areArgumentsShallowlyEqual` and it seems to be memoizing.

**Comment by markerikson** [comment]
@enmanuelduran : it largely depends on what kinds of values your "input selectors" are returning.  In this example, `getVisibleTodos` is unlikely to depend on anything different per component - it's really only depending on the core state itself, so it _would_ probably memoize correctly.  However, if every commponent is passing in a different ID value, then it probably won't.

**Comment by enmanuel-duran-olx** [comment]
The reason why I'm interested in this approach is because it appears to be more performant because it memoizes correctly even if I unmount the component. would you say it is a valid idea?

**Comment by markerikson** [comment]
No, not if you want it correctly memoizing per-component, and those components are feeding in different values per instance.  If you declare it outside of `mapState`, then there's one selector instance that's shared across all component instances, and it won't memoize right (same as if you'd declared it in another file and imported it here).

**Comment by enmanuelduran** [comment]
Ok, cool, thanks Sir.
