### ISSUE TITLE
Move combiner function before selector functions for type safety

### ISSUE THREAD

**Issue by nickmccurdy** [reduxjs/reselect#366]
In JavaScript, spread parameters are only valid as the last parameter of a function to prevent ambiguity. Type checkers like TypeScript and Flow rely on this assumption as well for checking function argument types.

Unfortunately, even though TypeScript ([as of version 3](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#richer-tuple-types)) and Flow support spread parameters, they cannot be used with Reselect's incorrect spread argument order. The combiner function is last, when it should be first so the selector functions can be a final spread parameter. This is necessary to take full advantage of all possible usages of Reselect besides the argument combinations hard coded in the TypeScript and Flow definitions, and also solves semantic confusion where Reselect has a different argument order for variable argument orders than most JavaScript APIs.

Alternatively, we could simply remove the API signatures that don't use the Array of selector functions. This would not break any code that is only using Arrays of selector functions.

**Comment by AlexeiDarmin** [comment]
I reached the same conclusion to move the combiner as the first function but didn't say anything since I figured it would be too disruptive to the library. I'm all for this. 

This also could allow for some better features moving forward supposing the spread operators gets better and better support by TypeScript

**Comment by nickmccurdy** [comment]
TS now supports mapping tuples, including arguments. This might be enough of a workaround to get strong typing on the current API, but it would still be much easier and simpler to fix the location of the combiner function or remove the other signatures.

**Comment by markerikson** [comment]
Based on the changes in #486 and #513 , I think this is now obsolete. We can keep the combiner last _and_ still get perfect inferred types, no API changes needed.
