### ISSUE TITLE
createBooleanSelector

### ISSUE THREAD

**Issue by binarykitchen** [reduxjs/reselect#370]
This library is awesome. Keep it improving :)

So yeah, suggesting here to create a new function like `createBooleanSelector` or similar. Because most of my selectors are just returning true/false.

For example

```js
export const selected = createSelector(
  list,
  (list) => list && list.some(apple => apple.get('selected'))
)
```

If `list` is undefined it returns undefined. But prefer to have it return false. So I wrap this with Boolean like:

```js
export const selected = createSelector(
  list,
  (list) => Boolean(list && list.some(apple => apple.get('selected')))
)
```

this for most of my selectors. Hence I would welcome a convenient function which saves me that.

**Comment by tkrugg** [comment]
I'm not exactly answering your question, apologies.
Can it more convenient if written as `!!list && list.some(apple => apple.get('selected'))` ?

**Comment by binarykitchen** [comment]
yeah, whether `!!` or `Boolean`, no big difference for me. Furthermore, everyone knows what `!!` is, hence `Boolean` probably a bit more readable.

All good, no biggie :)
