### ISSUE TITLE
loss of this context in input selectors

### ISSUE THREAD

**Issue by travi** [reduxjs/reselect#371]
while it may not be common for `this` to matter inside of an input selector, i was surprised to find that `reselect` clobbers the `this` context for the input selectors through [its use of `apply`](https://github.com/reduxjs/reselect/blob/3932567f7ca88d8dface5b46b0d2e0f23bd8ae07/src/index.js#L28). i see that the choice to use `apply` over spreading was made [in the interest of performance](https://github.com/reduxjs/reselect/blob/3932567f7ca88d8dface5b46b0d2e0f23bd8ae07/src/index.js#L27), but i'm curious if the tradeoff to clobber this was done intentionally because of it being uncommon.

for some context, my team has started to use [stamp-it](https://github.com/stampit-org/stampit) to provide base instances of our variation of [ducks](https://github.com/erikras/ducks-modular-redux) that include the selectors and action creators across many resource types. this introduces the use of `this` to reference the instance properties from within those common selector functions that end up being input selectors to `reselect` in some cases.

we were able to work around this problem by wrapping our input selectors in an anonymous function that uses `call` to explictly rebind `this` to the duck instance. this works, but seems like more work than should be necessary just to get back the expected behavior, had `this` not been clobbered. 

would you consider this outside of the supported use cases, or is this something that could be supported by `reselect`?

**Comment by markerikson** [comment]
Closing as this is stale, and I don't see it as a sufficiently meaningful use case.
