### ISSUE TITLE
Why the selector is getting state ?

### ISSUE THREAD

**Issue by devarashetty** [reduxjs/reselect#372]
I am trying to understand the following concept but getting confused a lot. Please explain .

My understanding :  Every preceding function in createSelector will send the data which will be received as arguments for the successor function

If that is right , why taxPercentSelector is getting `state` instead of output of `subtotalSelector`
```
   import { createSelector } from 'reselect'
 
const shopItemsSelector = state => state.shop.items
const taxPercentSelector = state => state.shop.taxPercent
 
const subtotalSelector = createSelector(
  shopItemsSelector,
  items => items.reduce((acc, item) => acc + item.value, 0)
)
 
const taxSelector = createSelector(
  subtotalSelector,
  taxPercentSelector,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)
 
export const totalSelector = createSelector(
  subtotalSelector,
  taxSelector,
  (subtotal, tax) => ({ total: subtotal + tax })
)
 
let exampleState = {
  shop: {
    taxPercent: 8,
    items: [
      { name: 'apple', value: 1.20 },
      { name: 'orange', value: 0.95 },
    ]
  }
}
```

**Comment by markerikson** [comment]
@devarashetty : no, your understanding is wrong.

Let me define some terms and explain how this works.  These terms are how I describe things, not anything that's in the docs.

- "input selector": the functions that you pass to `createSelector` either as an array, or the first `N - 1` arguments.
- "output selector": the final argument you pass to `createSelector`
- "final/actual selector": the function generated by `createSelector

When I call `actualSelector(a, b, c)`, Reselect will run all of my input selectors with the same `(a, b, c)` arguments.  It then saves the return values from all of the input selectors, and calls the output selector with those values.  So, every "input selector" becomes one argument to the "output selector".

Internally, it looks kinda like this:

```js
const inputSelectorResults = inputSelectors.map( inputSelector => inputSelector(...selectorArguments) );
const finalResult = outputSelector(...inputSelectorResults);
```

Example of how this is used:

```js
const selectA = (a, b, c) => a.first;
const selectB = (a, b, c) => b.someField;
const selectC = (a, b, c) => c;

const finalSelector = createSelector(
    [selectA, selectB, selectC],
    (resultA, resultB, resultC) => {
        // do something with values here
    }
);

const result = finalSelector({first : 42}, {someField : 123}, 99);
```
