### ISSUE TITLE
Use selector output as props passing down to child components

### ISSUE THREAD

**Issue by javidhsueh** [reduxjs/reselect#373]
Hello, I've seen the usage of selector between redux store and the smart component.
Recently I'm experimenting using selector as the transform function to process the props and pass the selector result to the child components.

Ex:
```
class DataTable extends Component {
  // selectors
  sortedDataSelector = createSelector(
    props => props.data,
    props => props.sortBy,
    (data, sortByKey) =>
      data.sort((a, b) => {
        const aVal = a[sortByKey];
        const bVal = b[sortByKey];
        return bVal - aVal;
      })
  );

  render() {
    return (
        <Table
            data={this.sortedDataSelector(this.props)}
        />
    );
  }
}
```
I'm just wondering is there any side effect could happen if I use selector in this way?

**Comment by markerikson** [comment]
Looks okay to me conceptually.  The one problem here is that the `data.sort()` call actually mutates the existing array, so don't do that.  Instead, inside the output selector, make a copy of `data` and sort that, like:

```js
    (data, sortByKey) => {
      const dataCopy = data.slice();
      dataCopy.sort((a, b) => {
        const aVal = a[sortByKey];
        const bVal = b[sortByKey];
        return bVal - aVal;
      })
      return dataCopy;
    }
```

But as far as using a selector instance to do some filtering and such when rendering, that's totally fine, yeah.

**Comment by javidhsueh** [comment]
Thanks for your speedy response. Looks awesome! Thanks for the comment.
