### ISSUE TITLE
should createSelector be called with an array of selectors or not?

### ISSUE THREAD

**Issue by dagadbm** [reduxjs/reselect#374]
I am a bit confused regarding the documentation because in the beginning it is said we should use createSelector like this:

createSelector(
selectorA,
selectorB,
(outputA, outputB) => {});

but everywhere else it is said the first argument should be an array like so:

createSelector([
selectorA,
selectorB],
(outputA, outputB) => (});

What should exactly be the use case?
Because in our entire code base we are using the first one but I'm not it is actually doing anything ...

Thanks and I'm sorry if this issue is really dumb but I am genuinely confused.

**Comment by markerikson** [comment]
Both "multiple arguments" and "one array" syntaxes are valid:

```js
createSelector(selectA, selectB, outputSelector)

createSelector( [selectA, selectB], outputSelector)
```
