### ISSUE TITLE
How to change the cache size

### ISSUE THREAD

**Issue by iremlopsum** [reduxjs/reselect#377]
Hey guys, I'm wondering how would it be possible to change the cache size? Is that impossible with `defaultMemoize` while using `createSelectorCreator`?

I see that this pull request is still open that would provide this option (https://github.com/reduxjs/reselect/pull/210/commits/ec1fb41ac3499e72656743b3b8fafd73d8242c24).

I need to expand the cache size per set of arguments to 6 since I'm using this in filtration and I have 6 different filters.

Thanks in advance

**Comment by jvitela** [comment]
You have to use createSelectorCreator with custom memoization, check the example from the docs: https://github.com/reduxjs/reselect#use-memoize-function-from-lodash-for-an-unbounded-cache
