### ISSUE TITLE
Document breaking changes in version 4.0.0

### ISSUE THREAD

**Issue by bxt** [reduxjs/reselect#382]
In the changelog file (https://github.com/reduxjs/reselect/blob/master/CHANGELOG.md) you can read "This project adheres to Semantic Versioning.". However, in the entry for version 4.0.0 there is no mention of any Breaking Changes. Are there any? Is it safe to update? Why the major version bump?

**Comment by Fandekasp** [comment]
:+1: I'm surprised by the jump from v3 to v4 for what appears like a small feature addition

**Comment by ellbee** [comment]
The bump was because of the TypeScript typings, they could have broken builds for people compiling with TypeScript.
