### ISSUE TITLE
`createSelector` without input selectors / dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [reduxjs/reselect#388]
I have a selector that transforms `A => B`, and I want to memoize it. The selector does not depend on any input selectors.

AFAICS, `createSelector` does not allow 0 input selectors. In this case, should I use something like `memoizeOne` instead?

``` ts
// A => B
// const fn0 = createSelector(a => b);
const fn0 = memoizeOne(a => b);
```

If so, I wonder if we should allow `createSelector` for this use case, so users don't have to bring in another library?

In https://github.com/reduxjs/reselect/issues/88, it was suggested that `createSelector` was not needed in this case, however then we would lose memoization.

Later, I want to compose this selector. IIUC, it *does* makes sense to use `createSelector` in this case:

``` ts
// A => C
const fn1 = createSelector(fn0, b => c)
```

**Comment by zentby** [comment]
if you want one-time calculation for memorization, either use a static calculation: 
```js
const mapStateToProps = (state) => {
    const prop = fn0(state);
    return {
         prop
    };
};
```
or pass in a const function:
```js
const fn1 = createSelector([()=>1], b => c)
```

**Comment by OliverJAsh** [comment]
@zentby 

> if you want one-time calculation for memorization, either use a static calculation:

`fn0` would not be memoized (unless we use `memoizeOne`), so it would re-run each time `mapStateToProps` is called.

> or pass in a const function:

I presume you're talking about something like this (to use my original example):

``` ts
// A => B
const fn0 = createSelector(a => a, a => b);
```

That works, but it feels like we shouldn't have to do this.

**Comment by steppefox** [comment]
Well, I like to revive dead threads. I believe memoization won't work properly in that case.
Let's say we have something like this:

```js
const mySelector0 = memoizeOne(a => b);
```

And we use it somewhere like that:

```js
mySelector0(state);
```

The thing is, `state` - is a big object that we change a lot. It has data that is not necessary for particular selectors. So memoization will override the cached value **each** time when we change **anything** in the state. I think that input `a` that we need in singular memoized selector is not a whole `state` that we need to process, but some particular data in the state, right? So to make memoization work properly and recalculate the cache ONLY when the necessary data changed, we **should** do something like this:

```js
const selectMyData = (state) => state.someField.mayBeNestedValue;

const mySelector0 = createSelector(
  selectMyData,
  (a) => b
);
```

In case if we need a bunch of different data from the state:

```js
const selectData1 = (state) => state.someField.mayBeNestedValue;
const selectData2 = (state) => state.differentField;

const mySelector0 = createSelector(
  selectData1,
  selectData2,
  (a1, a2) => {
    const b = { ...a1, ...a2 };
    return b;
  }
);
```

---

In case, if we need the whole state calculations with memoization, for instance for comparing hash-values, we don't need `reselect` for that at all. Memoization is a very simple function, it could be implemented by bare hands, or cherry-picked from any tools library like `lodash`.

In other cases, probably the implementation is not really correct and we're doing something weird. Sometimes we store the data "raw" from the backend and trying to dance with it implementing hacks - in that case the data should be processed/mapped/changed before putting it in the store.

**Comment by OliverJAsh** [comment]
> `state` - is a big object that we change a lot

Not necessarily, because selectors can be used [with any level of state](https://github.com/reduxjs/reselect/issues/187#issuecomment-257947556), not just the root state.

For example, I have this selector:

```ts
const getFullUserName = user => `${user.first_name} ${user.last_name}`;
```

**Comment by steppefox** [comment]
@OliverJAsh But we don't need `reselect` for that at all o_O We can use any memoization implementation here if it's necessary.

```js
const getFullUserName = memoize((user) => `${user.first_name} ${user.last_name}`);

const user = { first_name: 'Eldar', last_name: 'Amantay' };
getFullUserName(user); // Eldar Amantay

// Example with data from the store

const selectUser = state => state.user;
const getFullUserName = memoize((user) => `${user.first_name} ${user.last_name}`);

const selectUsername = createSelector(
  selectUser,
  getFullUserName
);
```

We usually don't need to memoize string results though. They're not expensive and don't trigger re-renders in components. It depends of course.

Can you please provide another case when you need a singular selector? oO

**Comment by OliverJAsh** [comment]
> I wonder if we should allow `createSelector` for this use case, so users don't have to bring in another library?

I understand this is possible with standard memoization, but my main question here was whether we could/should make `createSelector` support this use case so that users don't have to pull in another library—`createSelector` would then work for selectors in all shapes and sizes.

**Comment by markerikson** [comment]
I would either avoid memoizing, or write it as the one-level input selector @steppefox 	showed.

**Comment by steppefox** [comment]
@OliverJAsh I believe that `createSelector` shall remain as it is, because it prevents people to make a mistake when they'd try to memoize global state (or any often changeable object). Wrong usage of memoization would cause a memory leaks.

For simple memoization it's possible to use `defaultMemoize` from `reselect`:

https://codesandbox.io/s/beautiful-sara-7h9dl

```js
const { defaultMemoize } = require("reselect");

const getFullUserName = defaultMemoize(user => ({
  message: `${user.first_name} ${user.last_name}`
}));

const user = { first_name: "Eldar", last_name: "Amantay" };
const user2 = { ...user, last_name: "Yatnama" };

console.log(
  getFullUserName(user),
  getFullUserName(user) === getFullUserName(user)
); // Eldar Amantay, true
console.log(
  getFullUserName(user2),
  getFullUserName(user2) === getFullUserName(user)
); // Eldar Amantay

```
