### ISSUE TITLE
Composing selectors without further transformations

### ISSUE THREAD

**Issue by OliverJAsh** [reduxjs/reselect#389]
I have some selectors:

``` ts
// created via `createSelector`
declare const getBFromA: (a: A) => B
declare const getCFromB: (b: B) => C
declare const getDFromC: (c: C) => D
```

I now want to compose these. IIUC, my options are:

``` ts
const getDFromA = pipe(getBFromA, getCFromB, getDFromC);
```

or

``` ts
const getCFromA = createSelector(getBFromA, getCFromB);
const getDFromA = createSelector(getCFromA, getDFromC);
```

I'm not sure if it's OK/necessary to use `createSelector` with a selector as the transformation function argument—usually the transformation function is not a selector defined with `createSelector`, rather it is a "simple" (non-memoized) transformation function. Can you advise?

**Comment by markerikson** [comment]
Tbh the question seems unclear, and also stale, so I'm going to close this.
