### ISSUE TITLE
Suggestion: Ability prevent re-calculation with condition

### ISSUE THREAD

**Issue by felixkollin** [reduxjs/reselect#396]
So I would like to suggest some ability to prevent a selector from re-calculating on one specific condition in addition to changed arguments. 

### Scenario
In my case I use reselect to filter two sets of data and map them to props with redux. So I have:
```javascript
const mapStateToProps = (state, props) => ({
  data1: processedData1(state),
  data2: processedData2(state)
})
export default connect(mapStateToProps)(MyComponent)
```
data1 and data2 are fetched with an api call for each one, so they are updated separately. However, I keep an isLoading boolean in the redux store that is true while any of the two data sets are still being fetched.

I also have another selector (lets say call it combinedDerivedData) using both processedData1 and processedData2, so when any one of them re-calculates, those combinedDerivedData do as well.

### Problem
The problem is that once data1 is done fetching, reselect will re-calculate, thus making MyComponent re-render. Then data2 is fetched, reselect re-calculates, and MyComponent re-renders again. Additionally, any selectors using both processedData1 and processedData2 re-calculates when any of them changes. I would only like to re-calculate once isLoading is false.

Currently:
1. Data 1 fetched
2. processedData1 re-calculates
3. combinedDerivedData re-calculates
4. Data 2 fetched
5. processedData2 re-calculates
6. combinedDerivedData re-calculates

With solution:
1. Data 1 fetched
2. Data 2 fetched
(isLoading set to false)
3. processedData1 re-calculates
4. processedData2 re-calculates
5. combinedDerivedData re-calculates

Note that the solution also triggers less MyComponent re-renders.

### Current solution
My current solution is a bit **crude** and implements a createConditionalSelector which handles the first selector as the selector for the loading condition:
```javascript
function conditionalMemoize (func, equalityCheck = defaultEqualityCheck) {
  let lastArgs = null
  let lastResult = null
  return function () {
    if (!areArgumentsShallowlyEqual(equalityCheck, lastArgs, arguments)) {
      if (lastResult) {
        const condition = arguments['0'] // Condition should be the first argument
        if (typeof condition === 'boolean' && condition) {
          lastArgs = arguments
          return lastResult
        }
      }
      lastResult = func.apply(null, arguments)
    }
    lastArgs = arguments
    return lastResult
  }
}

export const createConditionalSelector = createSelectorCreator(conditionalMemoize)
```

And then you use it like this:

```javascript
export const processedData1 = createConditionalSelector(
  [getLoading, getData1, getSomeFilter],
  (loading, data1, filter) =>
    processData1(data1, filter) // some heavy computation
)
```

I'm pretty sure there are neater ways of doing this, so if you have suggestions please let me know. Or this might be something someone could look into integrating into reselect (per suggestion). I tried to look through as much as possible but I could not find any information on how to do this.

**Comment by jvitela** [comment]
I think this kind of logic does not belong to reselect, you should control it on the mapStateToProps function. Assuming `isLoaded` is set to **false** after all data sets are loaded:

```js
const mapStateToProps1 = (state, props) => ({
  data1: state.isLoaded ? processedData1(state) : null,
  data2: state.isLoaded ? processedData2(state) : null
})

// Somewhere else... 
const mapStateToProps2 = (state, props) => ({
   derived: state.isLoaded ? combinedDerivedData(state) : null
})
```
