### ISSUE TITLE
How to share the same selector *instance* among multiple component instances?

### ISSUE THREAD

**Issue by zxti** [reduxjs/reselect#398]
It's documented how to share selector code among multiple component instances.  It often makes sense for each component to have its own private memoized cache.

But for selectors that actually can share the cached value, is there a way to make them share this selector instance?

Some workarounds:

- Move this derived state into the store.  Hurts modularity (most components won't care about this derivation).
- Have one common ancestor of the interested components own the selector, and pass this down via props/context.  Hurts in the same way that "lifting state" is annoying - the lowest-common-component can be a moving target, and it also starts bleeding into the above non-modularity point.

**Comment by jvitela** [comment]
Can you maybe share an example of your use case?

**Comment by sunndeath** [comment]
> It's documented how to share selector code among multiple component instances. It often makes sense for each component to have its own private memoized cache.
> 
> But for selectors that actually can share the cached value, is there a way to make them share this selector instance?
> 
> Some workarounds:
> 
> * Move this derived state into the store.  Hurts modularity (most components won't care about this derivation).
> * Have one common ancestor of the interested components own the selector, and pass this down via props/context.  Hurts in the same way that "lifting state" is annoying - the lowest-common-component can be a moving target, and it also starts bleeding into the above non-modularity point.

Why can't you move the selector one level up?
