### ISSUE TITLE
createStructuredSelector sometimes does not work

### ISSUE THREAD

**Issue by oliverwatkins** [reduxjs/reselect#400]
I'm not sure if this is familiar to anyone, but createStructuredSelector sometimes does not work for me : 

https://stackoverflow.com/questions/55240609/reselect-createstructuredselector-is-not-updating

**Comment by markerikson** [comment]
Skimming your SO question, it looks like you're unnecessarily defining things as functions that call `createSelector()`.  Don't do that :)  

In other words, do this:

```js
const selectDomain = state => {
    console.info('(1)')
    return state ? state.shops : {};
};

export const selectShop = createSelector(
        selectDomain,
        shops => {
            console.info('(2)');
            return shops.shopList.find(shop => shop.selected)
        }
    );

export const selectShopInventory = createSelector(
        selectShop,
        shop => {
            console.info('(3)')
            return shop.inventory
        }
    );
```

**Comment by oliverwatkins** [comment]
This does not seem to help me. I get this error message instead : 

> Error: Selector creators expect all input-selectors to be functions, instead received the following types: [object]

At line 👍 

> export const selectShop = createSelector(

**Comment by markerikson** [comment]
You also need to adjust your call to `createStructuredSelector` from what you had in the issue.  It should be:

```js
const mapStateToProps = state =>
    createStructuredSelector({
        fruits: selectShopFruits,
    });
```
