### ISSUE TITLE
"Motivation" is way more critical than it seems.

### ISSUE THREAD

**Issue by cyrilchapon** [reduxjs/reselect#403]
[#motivation-for-memoized-selectors](https://github.com/reduxjs/reselect#motivation-for-memoized-selectors) section of readme states that

> `mapStateToProps` calls `getVisibleTodos` to calculate todos. **This works great, but there is a drawback: todos is calculated every time the state tree is updated. If the state tree is large, or the calculation expensive, repeating the calculation on every update may cause performance problems. Reselect can help to avoid these unnecessary recalculations.**

```
const getVisibleTodos = (todos, filter) => {
  switch (filter) {
    case 'SHOW_ALL':
      return todos
    case 'SHOW_COMPLETED':
      return todos.filter(t => t.completed)
    case 'SHOW_ACTIVE':
      return todos.filter(t => !t.completed)
  }
}

const mapStateToProps = (state) => {
  return {
    todos: getVisibleTodos(state.todos, state.visibilityFilter)
  }
}
```

Actualy I think there is even a (way) more serious drawback.

In the above, if `SHOW_COMPLETED` or `SHOW_ACTIVE` is ticked, then the returned value is `todos.filter(t => t.completed)`, which **creates a new array** and thus **breaks the reference of the prop**.

Intrinsequely, this prop is passed down straight to the `TodoList ` component, which **is re-rendered** when it occurs. And... it occurs very often... On every global state change actually, at the exact same rate of `mapStateToProps` calls.

Am I missing something, or could I update the README maybe ?

**Comment by js1599** [comment]
" On every global state change actually, at the exact same rate of `mapStateToProps` calls." 

It does not call the function on every global state change, instead it only recalculates it when it detects a delta between the current value, and the upcoming value. This is why reselect uses the concept of memoization, where the expense is only incurred if there's a change, if not the original value is returned w/ no expense. Furthermore, the re-render can be controlled by the developer based on what props they're deciding to flush to their component, and if that's problematic, the use of shouldComponentUpdate lifecycle method can curtail this

**Comment by cyrilchapon** [comment]
@js1599 I was pointing the fact that :
- **usually** indeed a react-redux app does not call `mapStateToProps` of a component a every global state change rate
- **but in this exact example implementation**, the fact how the filter is coded :
  ```
      case 'SHOW_COMPLETED':
        return todos.filter(t => t.completed)
  ```

  When the reducer is called (at every state update, anywhere, I really think), if that filter is activated, the filter applies and the reference to `todos` is broken. Causing the `the expense is only incurred if there's a change` part of your answer. Thus the memoization provided by reselect offers a double-win here. 1) indeed not recalculating the `filter()`, ok but also 2) not re-breaking `todos` refence at each state change rate, and thus causing a free re-render of the component.

**Comment by markerikson** [comment]
Yes, the entire point of that example in the readme is that it _does_ return a new array reference every time.  This is being described as a _bad_ thing, and the reason to want to have memoized selectors in the first place.

If someone thinks the readme isn't explicit enough, go ahead and file a PR.  Otherwise, I don't think there's really anything that needs to be done here.
