### ISSUE TITLE
Reselect passes data of different shared selectors into the compare function

### ISSUE THREAD

**Issue by mikalai-sauchanka** [reduxjs/reselect#408]
Please see a [codepen](https://codepen.io/mikalai-sauchanka/pen/mYVjxX?editors=0012). Check the console. Isn't it a bug?

**Comment by markerikson** [comment]
I don't know what this demo is trying to show.  Can you explain further?

**Comment by mikalai-sauchanka** [comment]
Yes, sure. I've created a small react/redux [app](https://stackblitz.com/edit/redux-playground-xgvba8?file=selectors.js). 

I probably misunderstood the concept of reselect...

1. Check two selectors: itemSubSettingsSelector and settingsSelector
2. itemSubSettingsSelector selects a subset of settings
3. settingsSelector uses custom comparer (createCustomSelector)

My understanding was that this custom comparer will receive outputs of itemSubSettingsSelector of the same item (same id), but in reality this comparer never returns true, which causes the component to rerender.

Is it by design? If yes, then please suggest how can I fix it.

**Comment by markerikson** [comment]
Mmm... I don't know if it's the actual issue, but your `makeSettingsSelector()` function is doing absolutely nothing.  It's returning an existing selector instance, not instantiating a new selector instance.

**Comment by mikalai-sauchanka** [comment]
Damn... Nice catch! Thanks a lot!

**Comment by mikalai-sauchanka** [comment]
@markerikson I've updated my own project, but still have the same issue... Would you please give a suggestion of potential reason(s)?

**Comment by mikalai-sauchanka** [comment]
OK... I managed to reproduce it. See the updated [demo](https://stackblitz.com/edit/redux-playground-xgvba8?file=reducers.js). I just added more selectors to the chain.

**Comment by mikalai-sauchanka** [comment]
@markerikson, sorry for bothering, but it's become really important now. My selectors are useless and the performance gap is significant. Could you check [here](https://stackblitz.com/edit/redux-playground-xgvba8?file=reducers.js) why the selectors don't work as expected?

**Comment by markerikson** [comment]
At a quick glance: I think the issue is that you're reusing the same instance of `colorSelector` for both components.  That will be called with different color objects for component1 and component2 every time, so the memoization will never work right.  It's the problem that I described here:

[Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance - Advanced Optimizations](https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/#advanced-optimizations-with-react-redux)

**Comment by mikalai-sauchanka** [comment]
@markerikson, thanks for the reply. Hm, the technique from the post is being used at the demo (see makeStyleSelector)...

**Comment by markerikson** [comment]
@mikalai-sauchanka : you're making a new _style_ selector, but they're both still using the same _color_ selector instance.

**Comment by mikalai-sauchanka** [comment]
@markerikson understood. Thanks a lot for your help and time!
