### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by jutunen** [reduxjs/reselect#412]
Hi,

isn't it so that it is pointless to use reselect, if you have only a single react-redux connect call with a single mapStateToProps definition that handle the entire state of your app?

**Comment by markerikson** [comment]
No.  Even with only a single connection, you may have transformations that you only want to run when that specific data has changed.

See my post [Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance](https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/) for some discussion.
