### ISSUE TITLE
TypeScript types should be moved to DefinitelyTyped or ported to TypeScript

### ISSUE THREAD

**Issue by nickmccurdy** [reduxjs/reselect#421]
This is pretty much the same as https://github.com/reduxjs/redux/issues/3500, so please read that for my explanation and the pending discussion.

Ultimately the decision for Reselect depends on how comfortable the maintainers are with TypeScript and if they want to support it directly (is so port, if not use DefinitelyTyped and remove the types from this package).

**Comment by MichaelDeBoey** [comment]
@markerikson @timdorr CTL moved their typings to DT, but added them as a `dependency` to their package. Could be an interesting move for `reselect`/`redux-thunk`/... too if you want to keep them in JS.
https://blog.johnnyreilly.com/2019/08/symbiotic-definitely-typed.html

**Comment by nickmccurdy** [comment]
In my opinion, it's better to break back compatibility and allow more freedom in versioning the peer dependency.

**Comment by markerikson** [comment]
Don't see them being moved to DT at this point, and if anything we oughta rewrite this in TS.
