### ISSUE TITLE
[proposal] createStructuredSelector to accept nested object

### ISSUE THREAD

**Issue by ruanyl** [reduxjs/reselect#423]
The current `createStructuredSelector`:

```javascript
createStructuredSelector({
  x: state => state.a,
  y1: createStructuredSelector({
    w: state => state.c
  }),
  y2: createStructuredSelector({
    z: state => state.b
  }),
})
```

**Propose to add support for nest object**, for example:
```javascript
createStructuredSelector({
  x: state => state.a,
  y1: {
    w: state => state.c
  },
  y2: {
    z: state => state.b
  },
})
```

Would this be a handy feature to you? I have made an initial commit here: https://github.com/ruanyl/reselect/commit/c3eb783775a2798d0b32a2d45cd6e0015238e19c

**Comment by markerikson** [comment]
I think this is too niche a use case at this point.
