### ISSUE TITLE
Passing down ownprops

### ISSUE THREAD

**Issue by spacedust** [reduxjs/reselect#425]
I have a store with users and a component `<User userId={} />` inside this component I use a selector with ownprops.userId to get the current user. My question: Inside my `<User />` component I have child components that also need to select the current user. Is there a better approach to prevent something like this?

```
<User userId={} />
    <UserChildComponent userId={} />
           <UserChildChildComponent userId={} />
```

I Would like to get in a scenario where I pass userId only to `<User userId={}/>` and that the child components can keep working with that current user through mapStateToProps

**Comment by jvitela** [comment]
Seems to me like a use case for React Context: https://reactjs.org/docs/hooks-reference.html#usecontext
