### ISSUE TITLE
Cannot read property <selectorName> of undefined

### ISSUE THREAD

**Issue by ThinkSalat** [reduxjs/reselect#426]
Hello,

I'm having a strange issue with one of my composed selectors.

So we have multiple selector files to stay organized. 

in my patientSelectors and userSelectors I have quite a few reselect selectors. 

If I import my patientSelectors into my userSelectors file, all of a sudden, one of my composed reselectors throws the error `Cannot read property memoizedGetUser of undefined`

Here's the selector that's crashing.
```
const memoizedGetPatientSymptomSeries = createSelector(
	state => getCurrentPatientId(state),
	state => displayPrefSelectors.getSymptomsToView(state), 
	state => userSelectors.getTrackerIds(state),
	state => state.information.information,
	userSelectors.memoizedGetUser,
	memoizedGetMTSymptomFromDailyLogs,
	informationSelectors.memoizedGetSeverityScaleDescription,
	(pid, selectedSymptoms, trackers, information, getUser, getData, getSeverityDescriptions) => {
             ...code
        }


```

So, for some reason, the third function that returns `userSelectors.getTrackerIds(state)` works fine, but the `userSelectors.memoizedGetUser` crashes saying that can't read memoizedGetUser of undefined.

The weirdest thing is that this only happens if I'm importing the patientSelectors into my userSelectors file. If I remove that import, everything is smooth sailing. If I add it back in, it throws the crash.

Why would userSelectors only be undefined for one selector but not another?

It turns out that converting it to `state => userSelectors.memoizedGetUser(state)` stops the crash from happening.

Anyone have any clue what's going on? I'd like to know more so I can prevent this from halting progress in the future.

**Comment by markerikson** [comment]
You are likely creating a circular dependency issue, and at the time of import, `userSelectors` is undefined because this file is being resolved before the file containing the user selectors has been resolved.

**Comment by ThinkSalat** [comment]
> You are likely creating a circular dependency issue, and at the time of import, `userSelectors` is undefined because this file is being resolved before the file containing the user selectors has been resolved.

What are the chances a circular dependency issue can be resolved by changing from `userSelectors.memoizedGetUser` to `state => userSelectors.memoizedGetUser(state)`?

**Comment by markerikson** [comment]
Potentially, yes.  The other answer is to not have a circular reference issue :)
