### ISSUE TITLE
Memoized selector's use of `arguments` makes all selectors have a parameter length of 0.

### ISSUE THREAD

**Issue by parkerault** [reduxjs/reselect#427]
Because all created selectors use `arguments` internally for performance, every selector has a `length` of zero. This makes it impossible to determine how many parameters the selector has, which means it's impossible to know if you are using a cache-busting dependency.

https://github.com/reduxjs/reselect/blob/ac77610bbb0a3cab9b280ea5ea379c2387017446/src/index.js#L59 

If `createSelector` were to capture the parameter length of every primitive function dependency, the parameter length of the dependency with the highest number of parameters could be assigned to the `length` property of the returned selector. Since all root selectors must be composed of function primitives, this should allow all downstream selectors to have the correct `length` property.

It's possible that this isn't necessary and I'm missing some best practices, but our app uses a lot of selectors with a second `props` parameter, and every selector that depends on one of those selectors will invalidate the cache if used incorrectly. However, it's not at all obvious when you are creating a selector that any ancestor selector in the dependency tree might have a second parameter and require special handing to avoid invalidating the cache. This makes it extremely difficult to troubleshoot an app with hundreds of selectors to determine why the selectors are being recomputed on every render. Example:

```js
// In src/someSelectors.js
const selectItems = state => state.items;
const selectItem = createSelector(
  selectItems,
  (__, { id }) => id,
  (a, id) => a[id]
)

// In src/otherSelectors.js
const selectItemProp = createSelector(
  selectItem,
  item => item.prop
)
```
Obviously this is a trivial example, but at a very large scale this can lead to enormous complexity.

I'd be happy to hear any non-technical solutions to this problem, but as it stands I'm having a lot of problems with unnecessary re-renders and it's a bitch to figure out where the memoization is failing.

**Comment by markerikson** [comment]
I'm not following how function length relates to cache busting.  Which cache, specifically, and how is the length related?

**Comment by parkerault** [comment]
@markerikson without the function length it's impossible to detect if a selector uses a props parameter, which causes the issue described in https://github.com/reduxjs/reselect#sharing-selectors-with-props-across-multiple-component-instances

**Comment by markerikson** [comment]
Sorry, I'm still not seeing the connection here.

Where and how are you trying to "detect if a selector uses a props parameter"?  What "cache method" are you trying to change, and how?

**Comment by parkerault** [comment]
@markerikson I've only spent 30 or so minutes working with the internals of reselect, so please be charitable if I'm misunderstanding the implementation.

Since the selector returned from `createSelector` is a lambda with no parameters (instead opting to apply the arguments parameter to the memoized result function), its length value will always be zero.

The `createSelector` function captures the list of dependencies, and in the body of the resulting selector it applies the selector's arguments to each dependency to populate the arguments passed to `memoizedResultFunc`. For each one of those dependencies, any function primitive will have a `length` property equal to its number of parameters, and taking the maximum length value out of the list of dependencies will give us the number of parameters used by the resulting selector. By assigning that value to the selector's length property, each additional selector that uses it as a dependency will be able to compare its length to all other dependencies, whether they be function primitives or other selectors. Unfortunately, `length` is a read-only property, so it would have to be aliased to something like `params` or `paramsLength`.

The cache I'm referring to is the cache used by `defaultMemoize`.

**Comment by markerikson** [comment]
So part of the confusion here is that a selector function doesn't necessarily take a specific number of arguments.  

First, like any other JS function, there's a distinction between how many parameters it _expects_ to see, and how many arguments you choose to _call_ it with.  I can declare a function as `function func1(a, b, c) {}`, taking 3 parameters, but I can call it as `func1(1, 2, 3)`, `func1()`, or `func1(1, 2, 3, 4, 5)`.  All are legal.

Second, Reselect doesn't need to know or care how many arguments you've actually passed to the final generated selector function.  It simply takes _all_ of the provided arguments, and forwards them to each of the input selectors:

```js
const input1 = (state, b, c) => state.d;
const input2 = (state, b) => b;

const selectSomething = createSelector(
    [input1, input2],
    (d, b) => { }
)

selectSomething({d : 42}, 2, 3, 4, 5);
// will call:
// input1({d: 42}, 2, 3, 4, 5)
// input2({d: 42}, 2, 3, 4, 5)
```

Beyond that, I'm still not sure where and when you're wanting to "compare lengths" of selectors.  I half-thought you were talking about how `connect` checks the length of a `mapState` function to see if it should be called as `mapState(state)` or `mapState(state, ownProps)`, but that doesn't seem to be the case here.

Per your latest edit:  yes, in general, all the input selectors for a given `createSelector` call _should_ be "arguments-compatible".  In other words, if `input1` expects its second argument to be a number, and `input1` expects its second argument to be an object with a nested field, it's likely that one of those two would break when used together.

If you can show some actual examples of the selectors you're dealing with, and some code snippets of what you were thinking for potential solutions, I may be able to offer some suggestions.

**Comment by markerikson** [comment]
Per the "factory function" aspect: we've got that info sorta-kinda described in the Redux docs, and I definitely talked about it in my post [Using Reselect Selectors for Encapsulation and Performance](https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/).  We plan to cover the topic in more detail in the upcoming revamp of the Redux core docs.  But yes, that is something that folks need to be aware of as a potential point of concern.

**Comment by parkerault** [comment]
The snippet from my first comment shows a trivial example of the problem:

In one module, we create a selector that requires a `{ id: string }` argument to function.
```js
const selectItems = state => state.items;
const selectItem = createSelector(
  selectItems,
  (__, { id }) => id,
  (a, id) => a[id]
)
```
In a second module, we create another selector that uses `selectItem` as a dependency.

```js
const selectItemProp = createSelector(
  selectItem,
  item => item.prop
)
```

The second selector will also require an `{ id: string }` parameter to function. However, this is not apparent to someone scanning the source code looking for a bug. In addition, someone using this selector in the future will need to know that it will cause the selector to recompute on every action dispatch if it is used naively in multiple components.

Re-reselect provides a solution to the recomputation issue by requiring a `keySelector` function, but in this example every descendent of `selectItem` will need to use the same key selector or we're back at square one. This creates an even messier problem since not only does every developer need to know that they should use `createCachedSelector` instead of `createSelector`, they also need to create a shared module for exporting key selector functions, which just adds more complexity. So, while this doesn't seem too bad on the surface, when you scale it up to hundreds of selectors it starts to become a real nightmare. That's the problem I'm trying to solve.

**Comment by markerikson** [comment]
Frankly, it sounds like you need TypeScript :)

Also, note that the "recomputes" thing isn't always a concern.  If, as in that trivial example, the output selector is just returning a simple lookup, then it doesn't matter if it's really memoizing or not.  If it's doing some further transformation work, and in particular transformation work that results in a new reference (such as mapping an array), then yes - it would definitely matter.

**Comment by parkerault** [comment]
Yes, I'm working with a "legacy" codebase (meaning it was written more than 1 year ago), and I am in the process of migrating it to typescript. Unfortunately it uses a lot of dynamic functional-style meta-programming that is very difficult to make type safe, so in the meantime I'm trying to stop the bleeding. And in this case there are some pretty bonkers selectors that are causing large parts of some complex pages to be re-rendered on every action dispatch.

**Comment by parkerault** [comment]
Turns out the exact solution to my problem is explained here: https://github.com/toomuchdesign/re-reselect/blob/master/examples/4-programmatic-keyselector-composition.md

FWIW computing the arity of the created selector was very simple: https://github.com/parkerault/reselect/commit/b18767a5e56bae2ec01fd7d3e3c645370ce1f165

**Comment by amsterdamharu** [comment]
I think if you need extra parameters to a selector it's best to [curry them](https://github.com/amsterdamharu/selectors#parameterized-and-memoized).

If you use a multiple parameter selector like selecting an item by an id:

```js
const selectItems = (state) => state.items;
const selectItemById = createSelector(
  [(_, id) => id, selectItems],
  (itemId, items) => items.find(({ id }) => id === itemId)
);
const Item = ({ id }) => {
  //nothing is memoized here
  const item = useSelector((state) =>
    selectItemById(id, state)
  );
};
const List = ({ items }) => (
  <ul>
    {items.map(({ id }) => (
      <Item key={id} id={id} />
    ))}
  </ul>
);
```

Even if a render cycle only calls selectItemById once or multiple times with the same id it is still outside of the scope of a component to know that that is the case and adding another component to your app that calls selectItemById with another id will mess up your memoization.

It would be better to do something like this:

```js
const createSelectItemById = (itemId) =>
  createSelector([selectItems], (items) =>
    items.find(({ id }) => id === itemId)
  );
const Item = ({ id }) => {
  const selectItemById = React.useMemo(
    () => createSelectItemById(id),
    [id]
  );
  const item = useSelector(selectItemById);
};
```

If you don't care about memoization because actions cause a re render in Item components anyway then you can do:

```js
const Item = ({ id }) => {
  const item = useSelector(createSelectItemById(id));
};
```
