### ISSUE TITLE
Selector without dependencies?

### ISSUE THREAD

**Issue by amcsi** [reduxjs/reselect#429]
How am I to write a selector that has no dependencies? I don't see this mentioned in the docs.

If I have a reselect selector that does a heavy calculation, but doesn't depend on anything other than the root state directly, then what should I use?

1. If I just do `state => {....do heavy calculation; return result; }`, This is bad though, cause I can expect the heavy calculation to run on every render, even if the state doesn't change.
2. Do `createSelector(state => state, state => {....do heavy calculation; return result; })`. That function requires at least one dependency, so I use `state => state` as the dependency; this is awkward, but gives me the memoization I need.
3. Maybe `defaultMemoize()` is what I need?

**Comment by jvitela** [comment]
Could you share more details about the calculations you do inside your selector? You should basically try to extract parts of that code that read and transform portions of the state into separate selectors and use those as dependencies.

**Comment by markerikson** [comment]
Selectors should definitely _not_ just depend on the entire root state, for the reason you described - that's _always_ going to change.

**Comment by amcsi** [comment]
I realized since then that I'm to simply write a simple selector callback function (e.g. `const myPropertySelector = rootState => rootState.propertyThatIWant`) and use that, avoiding any reselect behavior. And that function can both be used directly in `useSelector()`, or passed as a dependency to a `createSelector()`.

**Comment by markerikson** [comment]
Yup. Selectors don't have to actually be memoized - they can just be simple functions!
