### ISSUE TITLE
Use redux action in my selector.

### ISSUE THREAD

**Issue by jonathandalgaard** [reduxjs/reselect#433]
How can I use a redux action inside my selector.

I have tried:
```
import { setValue } from "./actions/appStateActions";

const mySelector = createSelector(
  [
    state => state.value
  ],
  (value) => {
    setValue(value);
  }
);
```

But it says "setValue" is not defined.

Is it possible to use redux actions in a selector?

**Comment by r3dm1ke** [comment]
This does not look like a problem with `reselect`. Double check your export in `./actions/appStateActions`

**Comment by markerikson** [comment]
**DO NOT dispatch actions from selectors!**  A selector is like a reducer, in that it should be a pure function that _only_ calculates a return value based on its inputs.

**Comment by cjxe** [comment]
> How can I use a redux action inside my selector.
Then what is the solution, [`createAsyncThunk`](https://redux-toolkit.js.org/api/createAsyncThunk)?

**Comment by markerikson** [comment]
@cjxe I'm not sure what you're trying to accomplish, but "how do I dispatch an action from a selector?" is the _wrong_ question to be asking in the first place.

(Also this thread is 5 years old, so I'm closing it - if you have specific additional questions, please open a "Discussions" thread)
