### ISSUE TITLE
[useSelector vs connect with reselect]Selector recomputing when the state stays the same if using useSelector?

### ISSUE THREAD

**Issue by haivx** [reduxjs/reselect#449]
I've tried [useSelector](https://react-redux.js.org/api/hooks#useselector) with reselect. 
But I faced an isssues that in every render in component, useSelector is also recall, and in my createSelector, selector also recomputing despite the state stays the same. 

 But if I using `connect` function in `react-redux` instead of useSelector, everything is ok. No recomputing selector.
Is I missing something here? Anyone can help?  Thanks!

**Comment by markerikson** [comment]
It's hard to answer without know what your code looks like.  Please show some code that demonstrates the issue, preferably as a CodeSandbox.

**Comment by haivx** [comment]
@markerikson  You can view demo [here](https://codesandbox.io/s/react-resect-redux-grass-zv93s-zv93s).
After add some records and changing select box, you can see the result in console. I realized that the problem is `createSelector` function. Can you explain why the selector is recomputed? If using `connect`, it's ok. Thank you.

**Comment by markerikson** [comment]
You're using `createSelector` wrong.

Selectors only memoize when it's the same selector instance reused over time.

You're generating a new selector instance every time you call `teamSelector()`.  Don't do that.  Create the selector instance once, and reuse it.
