### ISSUE TITLE
TypeScript typings - Wrong arity when passing implicit selector in selector

### ISSUE THREAD

**Issue by gomesalexandre** [reduxjs/reselect#459]
Hi!
I've discovered what's probably a bug in the TS typings.

Let's imagine I have a selector `getSomethingA`, that gets data from other selectors using the selector reference shorthand:
```
export const getSomethingA = createSelector(
	[
		getSomethingADataRequirementA,
		getSomethingADataRequirementB,
	],
	// Callback here
```

- Where `getSomethingADataRequirementA` signature is:

`(state, props) => cb`

- And where `getSomethingADataRequirementB` signature is:

`(state) => cb`

If I then call `getSomethingA` with `props` and `state`, like this, I will get  an error `Expected 1 arguments, but got 2.` :

```
export const mapStateToProps = function (state: State, props: Props) {
	return {
		...statetoPropsMappings,
		somethingA: getSomethingA(state, props)
        }
}
```

But if I use the full syntax from the selector, creating a lambda with both `state` and `props` and calling `getSomethingADataRequirementA` with it, the arity of the `OutputSelector` is fine and error goes away

```
export const getSomethingA = createSelector(
	[
		(state: State, props: Props) => getSomethingADataRequirementA(state, props),
		getSomethingADataRequirementB,
	],
	// Callback here
```

**Comment by hejrobin** [comment]
I'm having this issue aswell.

**Comment by hanyuwang1993** [comment]
Same issue here. Typescript version 4.1.2

**Comment by gomesalexandre** [comment]
Thanks for the confirmation @hejrobin and @hanyuwang1993. Looking back into this, **this is likely not a bug**, I couldn't reproduce it with proper typings.
It seems to happen only when one of the underlying selectors is improperly, or not at all typed.

Why could this be? Well, if you are using a library such as `reselect-map` to create your selector, you might find out that it is missing typings, and as such, your selector will be typed as any! 🚨
[`export function createMapSelector(): any;`](https://github.com/heyimalex/reselect-map/blob/master/src/index.d.ts#L23)

In this case, let's say your `getSomethingDataRequirementA` has the `any` type for any reason, the solution would be to type it something like this:

`const getSomethingDataRequirementA: ParametricSelector<any, any, any> = yourSelectorVar`

Looking at `reselect` typings, we can see that `createSelector` is overloaded, and the first definition is 
https://github.com/reduxjs/reselect/blob/e93fe66ea972cc9d012889238881acc6793cfb12/src/index.d.ts#L23

The second is kind of the same, except it accepts a `ParametricSelector`, which is a selector **with both state props (and an infinite possible amount of arguments of any tpye after)** instead of a `Selector` (a selector with just state). This is what we want 

https://github.com/reduxjs/reselect/blob/e93fe66ea972cc9d012889238881acc6793cfb12/src/index.d.ts#L27

By digging down and finding out which of your selector is wrongly typed, then typing as `ParametricSelector<S, P, R>` where 
- S = State
- P = Props
- R = ReturnType 
 
You'll fix this! 🎉

**Comment by marcellino-ornelas** [comment]
I wasn't able to fully solve this but have a little work around for simple selectors

```ts
export const getValueFromStore = (state: ReduxState, value: string): string => { /* code here */}

export const someSelector = createSelector(
         getValueFromStore,
	(value) => expensiveFunc()
);

// produces:
// const someSelector: OutputSelector<ReduxState, string, (res: BadgesState) => string>

// workaround:

export const someSelector = (createSelector(
	getValueFromStore,
	(value): string => { /* your code */ },
// trick typescript to think this is the function signature
) as (state: ReduxState, value: string) => string);

// produces
// const someSelector: (state: ReduxState, value: string) => string
```

This should only affect typescript typings and should not change the behavior of how `createSelector` works

**Comment by nzankich** [comment]
I had this issue but was able to fix by not making the second argument optional

typescript error:
```
export const getSomethingA = createSelector(
	[
		(state: State) => getSomething(state),
		(state: State, a?: number) => a
	],
// Callback here
)
```

no error:
```
export const getSomethingA = createSelector(
	[
		(state: State) => getSomething(state),
		(state: State, a: number | undefined) => a
	],
// Callback here
)
```

imo this does seem like a bug

**Comment by gomesalexandre** [comment]
I will close it since this isn't a bug.

In case you're experiencing this, please refer to the comments, in particular https://github.com/reduxjs/reselect/issues/459#issuecomment-758649998 to find out how to properly type your inner selectors.
