### ISSUE TITLE
[Feature Request] Redux batch action should be worked on reselect computed.

### ISSUE THREAD

**Issue by Emiya0306** [reduxjs/reselect#462]
Hey everyone,

I use redux batch api, but I found that do not work on reselect. I meet the performance issue.
I write the demo code below to describe my problem. The reason I use `batch` is reusing my action code.

```javascript
// studentActions.js
export function setStudentById(uid, student = {}) {
  return dispatch => {
    dispatch({ type: 'SET_STUDENT', uid, student })
  };
}
export function batchSetStudents(students = []) {
  return dispatch => {
    // batch api should emit render once in component
    batch(() => {
      students.forEach(student => (
        dispatch(setStudentById(student.uid, student))
      ));
    });
  };
}
```
```javascript
// teacherActions.js
export function setTeacherById(uid, teacher = {}) {
  return dispatch => {
    dispatch({ type: 'SET_TEACHER', uid, teacher })
  };
}
export function batchSetTeachers(teachers = []) {
  return dispatch => {
    // batch api should emit render once in component
    batch(() => {
      teachers.forEach(teacher => (
        dispatch(setTeacherById(teacher.uid, teacher))
      ));
    });
  };
}
```
```javascript
// classActions.js
export function updateStudentsAndTeachers(classId) {
  return async dispatch => {
    // update teachers
    const teachers = await fetchTeachersByClassId(classId)
    dispatch(batchSetTeachers(teachers))
    // update students
    const students = await fetchStudentsByClassId(classId)
    dispatch(batchSetStudents(students))
  };
}
```
```javascript
// classReselect.js
export const getClassStudents = createSelector(
  state => state.currentClass,
  state => state.students,
  (currentClass, students) => {
    // if excute setStudentById 1000 times, the reselect will computed 1000 times.
    // school students count is 10000, that will be 1000 * 10000, right?
    // but setStudents using redux batch, I think it should be just excute once.
    return students.filter(student => student.classId === currentClass.id)
  }
)
```

My workaround solution is move reselect code to react component class get/set.
But I think that is not a good idea. Because that computed variable is used in multiple components.  😂

**Comment by markerikson** [comment]
Where are you actually using this selector?

FWIW, I would strongly recommend changing how you are dispatching in the first place.  Don't dispatch a separate "setter" action for each item.  Dispatch _one_ action containing all the data, and update _many_ pieces of state in response:

https://redux.js.org/style-guide/style-guide#model-actions-as-events-not-setters

https://redux.js.org/style-guide/style-guide#allow-many-reducers-to-respond-to-the-same-action

**Comment by Emiya0306** [comment]
Yeah~ The code I write is just a simple demo. Write the batch update "setter" action is also good, the redux-dev-tool will show single action and good for time traveling.
But it will be more complex in real situation. For example, `setStudentById` will dispatch other sync/async action. Like the step below:

- Teacher has some fields that can write expression(maybe sql, mdx).
- The expression can write students' name, such as: select * from [student].[foo].
- If the student name is changed and updated when fetching, the teacher expression will send request, response error and set in redux.

Emm~ Developer will write a lot of code to realize the batch update reducer again.
In my opinion, code should be reused. (Maybe I'm too lazy, but I believe most developers are lazy also.😹)
Dispatch one async action in component, then the async action will dispatch other sync/async actions. Each sync action (`Dispatch one action containing all the data`) will do it job (`update many pieces of state in response`).

Maybe write the batch "setter" to single "setter" is the best practice, but I just give my idea. If the selector can support batch state change into one change, I think it will be more cool. 😸

**Comment by markerikson** [comment]
I'm still a bit confused what your specific concern is.

Where and how are you trying to use this selector, and what "performance concerns" are you referring to?
