### ISSUE TITLE
Reselect not recomputing in specific case

### ISSUE THREAD

**Issue by EricCarr1978** [reduxjs/reselect#464]
I have a typical React, React-Redux, ReSelect setup based on the React Boilerplate Cra template.

I seem to have run into a unique problem where reselect does not recompute when an action updating the state is invoked by a component call back that is not user initiated - meaning a components onInit/onReady type of callback. But it works fine when invoked through a user initiated activity such as a button click. My example code:

```
import { selectSomePart } from "./selectors";
import { actions } from "./slice";

export const MyComponent = () => {
  const somePart = useSelector(selectSomePart);

  const updateState = () => {
    dispatch(actions.increaseValue(1));
	console.log(somePart.someValue);   
  };
  
  return (
	<ThirdPartyComponent onInit={updateState} /> /* prints the original state value even though I can see the updated state value in redux dev tools!! */
	
	<button onClick={updateState} /> /* correctly increases and prints the updated value on each click */
  )
}


// Slice.js
// --------------------------------
export const initialState = {
  someValue: 0,
};

const myExampleSlice = createSlice({
  name: "exampleSlice",
  initialState,
  reducers: {
    increaseValue: (state, action: PayloadAction<number>) => {
      state.someValue = state.someValue + action.payload;
    },
});


// Selectors.ts
// --------------------------------
import { RootState } from "./types";
import { initialState } from "./slice";

const selectDomain = (state: RootState) => state.somePart || initialState;

export const selectSomePart = createSelector(
  [selectDomain],
  (somePartState) => somePartState.somePart
);

```

PS: I'm not sure if this is a bug or an implementation issue from my side. If its an implementation issue, I'll move this to StackOverflow although I appreciate any help here as well.

**Comment by markerikson** [comment]
This looks like it's _just_ a closure/React-lifecycle issue.

The `useSelector` at the top of the component will not execute until React has a chance to re-render.  React will re-render in a batch at the end of the event handler.  This click handler was defined the _last_ time that React rendered, and closed over the value of `somePart` _at the time of the last render_.

So, when you log `somePart.someValue`, you're logging the value as it already was, _not_ as the data is in the store after the dispatch has been completed.

Try adding logging to the selector, the component, the reducer, and the click handler, and you'll see how the timing fits together.
