### ISSUE TITLE
Why is it impossible to pass only one argument to createSelector?

### ISSUE THREAD

**Issue by RustamKarimov3** [reduxjs/reselect#475]
Does make it a sense if I pass only one selector to createSelector? 

const somePartOfStateSelector = createSelector((state => state.somePart))

**Comment by markerikson** [comment]
Nope, and in that particular case there's no reason to even use Reselect at all.  There's no point to memoizing a selector that only returns a value.  Memoization is only useful when you're _deriving_ data.

**Comment by RustamKarimov3** [comment]
thanks
