### ISSUE TITLE
How to call selector inside createSelector's callback

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [reduxjs/reselect#479]
How to call another selector from createSelector's callback??

What I want to do is...

```
const usersSelectors = usersAdapter.getSelectors<IRootState>(
  (state) => state.users
);

export const userSelector = (id: number) =>
  createSelector(
    (state: IRootState) => usersSelectors.selectById(state, id),
    (user) => user
  );

export const parentSelector = createSelector(
  [dataSelector],
  (datas) => {
    datas.map((data) => {
       const user = userSelector(data.userId); // <== how to call another selector?
       return {
          xxx: data.xxx,
          yyy: data.yyy,
          user: user
       }
    })
  }
)
```

I tried this, but memomization doesn't work.
```
export const parentSelector = createSelector(
  [dataSelector, userSlector], // <== add userSelector
  (datas, selector) => {
    datas.map((data) => {
       const user = selector(data.userId);
       return {
          xxx: data.xxx,
          yyy: data.yyy,
          user: user
       }
    })
  }
)
```

Could you tell me how to call selector inside another selector?

**Comment by markerikson** [comment]
The first issue here is that `userSelector` has _three_ different problems:

- You are calling `createSelector()` every time you run `userSelector()`.  That creates a new memoized selector instance each time, so this will never memoize
- Any time you use Reselect and have an output selector like `item => item`, it's wrong. The point of Reselect is to _derive_ state.
- On top of that, "select a user by ID" is a straight lookup operation that doesn't need to be memoized anyway.

The next issue is that selectors normally take the _entire_ Redux state tree as their first argument, but inside of a Reselect output selector, you don't _have_ the entire state tree available - just the data your "input selectors" returned.

**Comment by Yoshihide-Nishimoto** [comment]
@markerikson 
Thank you for replying.

> You are calling createSelector() every time you run userSelector(). That creates a new memoized selector instance each time, so this will never memoize

I already implemented this code.
memo is working fine.

```
const exampleSelectors = adapter.getSelectors<IRootState>(
  (state) => state.example
);

export const selector = createSelector(
  exampleSelectors.selectAll,
  (examples) =>
    examples.filter((example) => {
       // do something
    }) 
);
```

So I thought this code's memomization would work fine, is it wrong?

```
export const userSelector = (id: number) =>
  createSelector(
    (state: IRootState) => usersSelectors.selectById(state, id),
    (user) => user
  );
```

> On top of that, "select a user by ID" is a straight lookup operation that doesn't need to be memoized anyway.

Do you mean, I don't need to create user(byId) selector in this case?
Actually, I already made this userSelector for another component, so I want to reuse this.
Is there no way to do this?

**Comment by markerikson** [comment]
No, you're missing what I'm saying here.

`const userSelector = () => createSelector()` _will not memoize_.  ever. the way you're trying to use it.

and on top of that, you don't _need_ a memoized `userSelector` here, because it's just "return an object based on an ID".  there's no derived state here at all.

**Comment by Yoshihide-Nishimoto** [comment]
@markerikson 
thank you.

I understood why this dosn't memomize.
```
export const userSelector = (id: number) =>
  createSelector(
    (state: IRootState) => usersSelectors.selectById(state, id),
    (user) => user
  );
```

but I can't understand this part.

> and on top of that, you don't need a memoized userSelector here, because it's just "return an object based on an ID". there's no derived state here at all.

If some components get state value without createSelector.
and If state ( not releated to user) is changed, the componet using the state will re-render.

So I thought memoization is necessary.

Am I wrong?

```
const UserCard = ({id}) => {
  const user = useSelector(userSelector)(id);
  // render 
}
```

**Comment by markerikson** [comment]
`selectUserById` boils down to `return state.users.byId[userId]`.  There's no "derived state" there - it's just a straight lookup.  Therefore, there is _nothing_ that needs to be memoized about that.  Either the item is the same reference, or it has been updated to a new reference.

Again, if you aren't creating _derived_ values, you don't need to use memoization.

**Comment by Yoshihide-Nishimoto** [comment]
hmmm 
I can't understand what you are saying.

```
There's no "derived state"
```

`state.users.byId[userId]` this isn't "derived"?

in this code below, user's reference should keep same unless the id or users state change to avoid re-rendering.
I wanted to know the way how to memoize the value in this case.

```
const UserCard = ({id}) => {
  const user = useSelector(userSelector)(id);
  // render 
}
```

Anyway I found another way to do this without reselect.
So I'll close this issue.
Thank you.

**Comment by markerikson** [comment]
"Derived state" would be something like:

```js
const selectTodoDescriptions = createSelector(
  state => state.todos,
  todos => todos.map(t => t.text)
)
```

Here, we have our original value (the array of todos), and we produces a _derived_ value - a new piece of data that is based on the _original_ value.

Just returning an item is not "deriving" a value.
