### ISSUE TITLE
Improve TypeScript for v5.0.0

### ISSUE THREAD

**Issue by eXamadeus** [reduxjs/reselect#484]
## Upgrade Types to Support TypeScript 4.1+ Capabilities

In version v5.0.0, reselect can take advantage of some of the interesting new features of TypeScript. Using 4.1+ we can accomplish these goals:

#### Goals
- eliminate the need for N-valued type overloads
- fully and safely type variadic (non-array) `createSelector` calls
- support more than 12 selectors in variadic `createSelector` calls
- fix bugs w/ typings (#420, #384 are some examples)
- support TypeScript 3.9+ and validate it in CI

---

### Some caveats

- #401 proposes interesting changes to the API, we should make sure to not conflict with these changes
- #483 replaces the CI pipeline with GitHub Actions. We need to support testing multiple versions of TypeScript with that new CI structure (this is already worked out in #480)

**Comment by markerikson** [comment]
Based on the changes I've made in #486 and locally, I actually see most of this as being doable in a 4.x release, and in fact I've pulled them in already.  It does require bumping our TS minimum to 4.2+, but frankly I consider changing TS version targets to _not_ require a major release.

**Comment by eXamadeus** [comment]
This has been completed! Released in https://github.com/reduxjs/reselect/releases/tag/v4.1.1
