### ISSUE TITLE
Tests: Recomputations starts with > 0

### ISSUE THREAD

**Issue by flexwie** [reduxjs/reselect#493]
I am writing tests for a selector with dynamic arguments like suggested in the documentation.

So after I asserted that the selector is returning the correct data I wanted to assert, that the memoization is also working as intended and does only recomputes once when I change the affected parts of my state. 
But `selector.recomputations()` returns something > 0 at the start of my test. I assume that is because I was already using the selector in the tests before? Is there a way to reset the selector? Or do I have to import it for each test seperately? 

I am using Jest for my tests.

**Comment by markerikson** [comment]
Yes, that sounds correct - selector instances are stateful by definition.  So, if you've used it in one test, it will still have that memoized data as it starts the second test.

**Comment by flexwie** [comment]
So whats the suggested way of dealing with this? Importing the selector before each test?

**Comment by stropho** [comment]
you basically want to reset the counter for every test, right ?
In Jest that would be something like
```
afterEach(() => {selector.resetRecomputations()})
```

**Comment by flexwie** [comment]
I was not aware of that function! Thank you!
