### ISSUE TITLE
How to type a factory function that returns selector?

### ISSUE THREAD

**Issue by MishaChernov** [reduxjs/reselect#502]
https://github.com/reduxjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

```
const expensiveItemSelectorFactory = (minValue: string): ? => {
  return createSelector(
    shopItemsSelector,
    items => items.filter(item => item.value > minValue)
  )
}

**Comment by markerikson** [comment]
You shouldn't have to declare a return type manually here. Let TS figure that out :)

**Comment by nickmccurdy** [comment]
Also if for some reason you wanted to change this type or be more explicit, you can hover the `createSelector` call in any TypeScript language service editor to see the type it returns.

This could be closed.

**Comment by junibrosas** [comment]
you can use `typeof` in typescript to grab the type of the variable.
