### ISSUE TITLE
Can I use reselect with useReducer?

### ISSUE THREAD

**Issue by sandinmyjoints** [reduxjs/reselect#504]
I'm considering converting an app using redux to not use redux anymore, just react state. https://github.com/reduxjs/reselect#q-can-i-use-reselect-without-redux says reselect can be used without redux -- great. useReducer returns state. Can I rely on the selectors I've written with reselect to still work if I pass them that state instead of state from a redux store?

**Comment by markerikson** [comment]
Reselect is "just" a vanilla JS memoization lib - there's nothing Redux-specific about it. So, yes.
