### ISSUE TITLE
4.1.x doesn't work with Props types

### ISSUE THREAD

**Issue by fantua** [reduxjs/reselect#533]
Hi! After upgrade to `4.1.1` typing for props doesn’t work:

![image](https://user-images.githubusercontent.com/7703761/139047714-b2629fe0-e8f4-4025-973a-a2cf64f52c14.png)

**Comment by eXamadeus** [comment]
It would be possible to align these type parameters. The `OutputSelector` in `~4.1.0` represents the combination of the `OutputParametricSelector` and the `OutputSelector` types in older versions, but they are basically the same thing (just one with an extra params argument at the end). Honestly, not 100% sure why I didn't align these better from the get go.

@markerikson I'm not sure we would do the `Old | New` concept, but changing it to be backward compatible _should_ be fine. It might annoy people moving from old to new back to the old type. Granted the sooner we do it, the fewer people that would run into that issue.

The diff would be pretty small for the type

```diff
diff --git a/src/types.ts b/src/types.ts
index 643f121..62fbf3e 100644
--- a/src/types.ts
+++ b/src/types.ts
@@ -16,8 +16,8 @@ interface OutputSelectorFields<Combiner, Result> {
 export type OutputSelector<
   S extends SelectorArray,
   Result,
-  Params extends readonly any[],
-  Combiner
+  Combiner,
+  Params extends readonly any[] = never
 > = Selector<GetStateFromSelectors<S>, Result, Params> &
   OutputSelectorFields<Combiner, Result>
```

**Comment by markerikson** [comment]
Should be fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.2
