### ISSUE TITLE
Type checking broken in 4.1

### ISSUE THREAD

**Issue by ViktorQvarfordt** [reduxjs/reselect#541]
In this example, reselect@4.0 correctly gives a typescript error for the last line, while reselect@4.1 reports no error

```ts
const selectProp1 = createSelector(
  [state => state, (state, props: { prop1: number }) => props],
  (state, { prop1 }) => [state, prop1]
)

const selectProp2 = createSelector(
  [selectProp1, (state, props: { prop2: number }) => props],
  (state, { prop2 }) => [state, prop2]
)

selectProp1('state', { prop1: 1 })
selectProp2('state', { prop2: 2 })
```

Here is a screenshot of the error, for reference:

![image](https://user-images.githubusercontent.com/344809/140572997-3dc275b5-ad2a-4840-8b94-92f053497973.png)

There are plenty other typing errors in 4.1 already reported in issue https://github.com/reduxjs/reselect/issues/540.

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.3
