### ISSUE TITLE
Build of library with declarations: true

### ISSUE THREAD

**Issue by abelgibayev** [reduxjs/reselect#543]
Hello! 

I need to build a core library for multiple applications with common slices and selectors inside. To have a good typization of selectors I need to set `declarations: true` in `tsconfig.json`. But it doesn't work, because OutputSelectorFields is not exported. The error I get from TS is `Exported variable 'selectAccountUser' has or is using name 'OutputSelectorFields' from external module "path-to-folder/node_modules/reselect/es/types" but cannot be named.`

Reselect version 4.1.2

**Comment by JamesGelok** [comment]
Same here. 

Downgrading to 4.1.1 was my only option:

```json
  "dependencies": {
    "...": "",
    "reselect": "4.1.1",
    "...": "",
  },
```

**Comment by markerikson** [comment]
I'll try to look at this tomorrow. I'm not 100% sure that I actually want to export the `OutputSelectorFields` type as the solution here, as I've been looking at trying to rearrange the typedefs some.

**Comment by onuralpbicer** [comment]
Having the same issue

**Comment by markerikson** [comment]
Could someone put together a repo that demonstrates this problem happening?  ie, something with a "shared selector" lib and a consuming lib.  That would help me investigate the problem and try to make sure it's resolved correctly.

**Comment by Methuselah96** [comment]
This isn't a small repo, but I had to work around it in [this PR](https://github.com/reduxjs/redux-devtools/pull/951) in `redux-devtools`.

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.3
