### ISSUE TITLE
`createStructuredSelector` doesn't infer props typings

### ISSUE THREAD

**Issue by fantua** [reduxjs/reselect#548]
`createStructuredSelector` doesn't infer props typings from selectors:

![image](https://user-images.githubusercontent.com/7703761/141695004-903c9198-f833-4e21-89e5-46279e4b1081.png)

https://codesandbox.io/s/distracted-tess-53co6?file=/src/mapData.ts

**Comment by markerikson** [comment]
Fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.3

**Comment by JMS-1** [comment]
Hm, with 4.1.3 I got a similiar Problem

```typescript
const some = createSelector(
    (a: number) => a,
    (_a: number, b: number) => b,
    (a, b) => a + b
)

export const test = some(1, 2)
```

![image](https://user-images.githubusercontent.com/3493757/141947763-47c52029-e2de-4d7a-81aa-5b83c06987f5.png)

**Comment by markerikson** [comment]
This issue was about `createStructuredSelector`.  Can you open a new issue with a reproduction?
