### ISSUE TITLE
CreateSelector with Parameters Failing Unit Tests

### ISSUE THREAD

**Issue by mandyMooreFan** [reduxjs/reselect#561]
Thanks so much for all the hard work on reselect. I tried to look through the other issues reported and didn't feel that I had seen my issue documented exactly the same. I can produce a stand alone repo if needed, but wanted to submit an issue first to make sure it wasn't a known issue or user error. 

## Overview:
If a selector has a parameters passed to it upgrading to Reselect 4.1.+ breaks functionality.

### Still Working:
Any selector that does not have any parameters passed to it works correctly.

#### Selector:
```
export const selectResource: Selector<
  RootState,
  ResourceState
> = createSelector([selectSlice], state => state);
);

```
#### Unit Test:
```
 it('should select the resource state', () => {
    expect(selectors.selecttResource(state)).toEqual(
      state.resource,
    );
  });
```

### Not Working After Update:
This test was working properly before updating

#### Selector:
```
export const selectFileById = (
  _: RootState,
  id: string,
): Selector<RootState, FileMetadataView | undefined> =>
  createSelector(
    [selectSlice, selectId],
    (state, id: string): FileMetadataView | undefined => {
      return state.files.filter(file => {
        return file.fileId === id;
      })[0];
    },
  );
```
#### Unit Test:
```
  it('should selectFileById', () => {
    expect(selectors.selectFileById(state, '12345')).toEqual(testFile);
  });

Expected: { "fileId": "12345" }
Received: [Function memoized]
```

### Dependencies
Some relevant dependancies. 

```
package.json
    "@reduxjs/toolkit": "1.7.1",
    "react-redux": "7.2.6",
    "typescript": "4.5.4",
    "react-scripts": "4.0.3",
```
#### Current Reselect from ReduxToolkit
```
reselect "^4.1.5"
```

#### Prior Reselect from ReduxToolkit
```
reselect "^4.0.0"
```

**Comment by markerikson** [comment]
Your `selectFileById ` appears to be wrong to start with. That's not a "selector function" - that's a _factory_ function that _creates and returns a new selector function instance_, and given that code I don't see how that unit test could ever have passed.

You need `selectFileById` to be the _result_ of that `createSelector` call instead:

```ts
const selectFileById = createSelector(
    [selectSlice, selectId],
    (state, id: string): FileMetadataView | undefined => {
      return state.files.filter(file => {
        return file.fileId === id;
      })[0];
    },
  );
```

**Comment by mandyMooreFan** [comment]
@markerikson Thanks so much for the clarifications and pointing out my mistakes here. I've successfully updated and sorry that I missed the section of the documentation that covered this. The functions below aren't fully cleaned up, but just for anyone who comes behind and maybe made the same mistake. The Typescript updates really do just work TM.  

### Incorrect:
```js
export const selectId = (state, id) => id;
```

### Corrected:
```js
export const selectId = (state: RootState, id: string): string => id;

export const selectFileById: Selector<RootState, FileMetadataView | undefined> =
  createSelector(
    [selectSlice, selectId],
    (state, id: string): FileMetadataView | undefined => {
      return state.files.find(file => file.fileId === id);
    },
  );

  const file = useSelector<RootState, FileMetadataView | undefined>(state =>
    selectFileById(state, props.resource?.fileId),
  );
```

Not having types on the "selectId" and "selectSlice" was the missing piece for me. It was screwing up the ability to type "selectFileById".

**Comment by markerikson** [comment]
FWIW, you shouldn't even need half the annotations you've got there :)

- You don't need to use the `Selector` type at all except in _very_ rare occasions
- You don't have to declare a return type for the output selector .  In particular, TS already should know that `state.files` is a `FileMetadataView[]`, and `array.find()` always returns `T | undefined`.  So, no return declaration needed.
- You _shouldn't_ supply generic types to `useSelector`.  At most, you declare `(state: RootState) =>` in your selector and let TS infer the result. Even better, create a pre-typed version of the `useSelector` hook per https://redux.js.org/tutorials/typescript-quick-start#define-typed-hooks .



So, this should simplify down to:

```ts
export const selectId = (state: RootState, id: string): string => id;

export const selectFileById = createSelector(
    [selectSlice, selectId],
    (state, id) => {
      return state.files.find(file => file.fileId === id);
    },
  );

  const file = useAppSelector(state =>
    selectFileById(state, props.resource?.fileId),
  );
```

Additionally, `selectFileById` doesn't even need to be a Reselect-based selector in the first place!  There's no actual memoization involved here - it's just returning a single result.

I would honestly just make it a basic function like this:

```ts
const selectFileById = (state: RootState, id: string) => 
  return state.whateverSlice.files.find(file => file.fileId === id);
}
```

That's all.  You _could_ still use `selectSlice()` here if you really want to, but I don't see any real benefit to it atm.
