### ISSUE TITLE
Types are not adjusted for defaultMemoize

### ISSUE THREAD

**Issue by maaaaagda** [reduxjs/reselect#566]
The `defaultMemoize` is supposed to support `DefaultMemoizeOptions` as its second parameter. The exported types are incorrect though, see below:
 
```js
export function defaultMemoize<F extends (...args: any[]) => any>(
  func: F,
  equalityCheck?: <T>(a: T, b: T, index: number) => boolean
): F
```

I have to import defaultMemoize explicitly to make it work with:
`const customSelector = createSelectorCreator(defaultMemoize, { resultEqualityCheck: isEqual });
`

**Comment by maaaaagda** [comment]
I have typescript 4.3.2

**Comment by markerikson** [comment]
Can you put together a CodeSandbox or a Github repo that actually shows this happening?

**Comment by markerikson** [comment]
Closing due to lack of response and reproduction.
