### ISSUE TITLE
Compose of createSelector return state with type of never

### ISSUE THREAD

**Issue by dangkhoipro** [reduxjs/reselect#567]
I encounter a problem when upgrading @reduxjs/toolkit from 1.4.0 to 1.7.2. (reselect 4.0.0 to 4.1.5), typescript 4.5.5
Here is the code from your github with some additional types to work with typescript.

`const selectShopItems = (state: any) => state.shop.items;
const selectTaxPercent = (state: any) => state.shop.taxPercent;

const selectSubtotal = createSelector(selectShopItems, (items) =>
  items.reduce((subtotal: number, item: any) => subtotal + item.value, 0)
);

const selectTax = createSelector(
  selectSubtotal,
  selectTaxPercent,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
);

// it yields error here: ...(state: any) is not assignable to (state: never)
const selectTotal = createSelector(
  selectSubtotal,
  selectTax,
  (subtotal, tax) => ({ total: subtotal + tax })
);`

Upon more inspection, I see that selectTax has (state: never) as its parameter. I guess somehow adding selectSubtotal (created by createSelector) to its parameters leads to this weird error.
Here is the sandbox: https://codesandbox.io/s/typescript-playground-forked-obcgrh?file=/index.ts

**Comment by markerikson** [comment]
Yes, you **must _not_ use `any` as an argument here - you _must_ always provide a real type for each argument**.  `createSelector` tries to infer the types from each argument, so they have to be "real" types.

**Comment by dangkhoipro** [comment]
Thanks for your reply. It fixes my problem.

**Comment by knownasilya** [comment]
This is very limiting, I get `state: never` and cannot override it
