### ISSUE TITLE
Question & Feature. Does every selector that receives an argument have to have the same shape?

### ISSUE THREAD

**Issue by mrdulin** [reduxjs/reselect#578]
test case - [chained selector with props](https://github.com/reduxjs/reselect/blob/v4.1.5/test/test_selector.ts#L239)

The `selector1` and `selector2` take an argument called `props` which the TS type is `{ x: number; y: number }`.

If I change the `props` of `selector1` to `z: number` like below:

```ts
const selector1 = createSelector(
  (state: StateSub) => state.sub,
  (state: StateSub, z: number) => z,
  (sub, x) => ({ sub, x }),
);
const selector2 = createSelector(
  selector1,
  (state: StateSub, props: { x: number; y: number }) => props.y,
  (param, y) => param.sub.a + param.x + y,
);
const state1 = { sub: { a: 1 } };
expect(selector2(state1, { x: 100, y: 200 })).toBe(301);
expect(selector2(state1, { x: 100, y: 200 })).toBe(301);
```

TSC will throw an error:
```bash
Argument of type '{ x: number; y: number; }' is not assignable to parameter of type 'number & { x: number; y: number; }'.
  Type '{ x: number; y: number; }' is not assignable to type 'number'.
```

So it seems if you create chained selectors and all of them take a parameter, the TS type of the parameter must be the same. 
Feature: please clarify the documentation.

**Comment by markerikson** [comment]
Yes, that's exactly the requirement.  Internally, `createSelector` loosely does:

```js
const extractedValues = inputFunctions.map(func => func(...args));
```

So, if you call `selectSomeValue(state, "a", 42)`, _every_ input function gets called with all of those values.

I'm going to close this since that answers the questions, but yeah, if you could file a PR to improve the docs wording we'd appreciate it!
