### ISSUE TITLE
The type of `createSelector` in ts4.1 doesn't support `memoizeOptions` as the last parameter

### ISSUE THREAD

**Issue by Yupeng-li** [reduxjs/reselect#580]
Hi, 

I got `TS2769: No overload matches this call` when I followed this example in docs.
```
// Selector behavior can be customized
const customizedSelector = createSelector(
  state => state.a,
  state => state.b,
  (a, b) => a + b,
  {
    // New in 4.1: Pass options through to the built-in `defaultMemoize` function
    memoizeOptions: {
      equalityCheck: (a, b) => a === b,
      maxSize: 10,
      resultEqualityCheck: shallowEqual
    }
  }
)
```
The type defined in this file `./src/typesVersions/ts4.1/index.d.ts` doesn't support `memoizeOptions`

Am I missing something or does it need to be fixed? 

Thank you

**Comment by markerikson** [comment]
What version of TS are you using? Can you put together a project that shows this happening?

**Comment by Yupeng-li** [comment]
Hi @markerikson, 

Thank you for the quick reply. Yes, we are using typescript 4.1.6.  I'll see if we can use the newer version of TS.
