### ISSUE TITLE
How to type the input selector of createSelector?

### ISSUE THREAD

**Issue by GabrielLim-ML** [reduxjs/reselect#581]
Hello, I am aware that we could explicitly type `createSelector` by doing `createSelector<inputType, outputType>`.
However, if my input is another selector instead of global state, what should I put for the `inputType` ?

Thanks!

**Comment by markerikson** [comment]
You actually _shouldn't_ use explicit generics with `createSelector` that way.

As of Reselect 4.1, it's intended to entirely infer the correct types from the arguments of your "input selectors".  So, as long as every input selector has the right type for its arguments, everything else Should Just Work (TM).

As an example:

```ts
// assume this root state:
interface RootState {
  todos: Todo[]
}

const selectCompletedTodos = createSelector(
  (state: RootState) => state.todos,
  (todos) => {
    // `todos` is already the right type in here
    return todos.filter(t => t.completed === true)
  }
)

const selectCompletedTodoIds = createSelector(
  selectCompletedTodos,
  (todos) => {
     // `todos` is _again_ the right type, because TS knows the right input and output
     // types from `selectedCompletedTodos`
    return todos.map(t => t.id)
   }
)
```

In other words, generally make sure that your input selectors look like `(state: RootState) => whatever`, or whatever the actual arguments are, and it should all just work from there.
