### ISSUE TITLE
Contradiction between usage examples in README and Redux docs

### ISSUE THREAD

**Issue by DenyVeyten** [reduxjs/reselect#598]
Basic Usage examples https://github.com/reduxjs/reselect#basic-usage (`selectSubtotal`, `selectTax`) contradict guide in Redux docs https://redux.js.org/usage/deriving-data-selectors#balance-selector-usage

I think both should be updated to some middleground, explaining that memoization is good over heavy operations (e.g. iterating long lists), but is overhead for simple ones (e.g. small math calculations, iterating short lists).

**Comment by markerikson** [comment]
Yeah, the README here is rather dated, but we've got a lot of other priorities and this really isn't on the list to update any time soon.

**Comment by aryaemami59** [comment]
This one has been resolved by #636.
