### ISSUE TITLE
Conflicting examples in the docs

### ISSUE THREAD

**Issue by evandavis** [reduxjs/reselect#629]
The documentation as written creates confusion around when and _when not_ to use memoization. Specifically, the section [Balance Selector Usage](https://redux.js.org/usage/deriving-data-selectors#balance-selector-usage) contains the following code:

```js
// ❌ DO NOT memoize: will always return a consistent reference
const selectTodos = state => state.todos
const selectNestedValue = state => state.some.deeply.nested.field
const selectTodoById = (state, todoId) => state.todos[todoId]

// ❌ DO NOT memoize: deriving data, but will return a consistent result
const selectItemsTotal = state => {
  return state.items.reduce((result, item) => {
    return result + item.total
  }, 0)
}
const selectAllCompleted = state => state.todos.every(todo => todo.completed)
```

This makes sense to me! However, the [Create Selector Overview](https://redux.js.org/usage/deriving-data-selectors#createselector-overview) shows the following examples:

```js
const selectABC = createSelector([selectA, selectB, selectC], (a, b, c) => {
  // do something with a, b, and c, and return a result
  return a + b + c
})
```

```js
const selectA = state => state.a
const selectB = state => state.b

const selectA1 = createSelector([selectA], a => a.first)

const selectResult = createSelector([selectA1, selectB], (a1, b) => {
  console.log('Output selector running')
  return a1 + b
})
```

These examples seem to be explicitly discouraged, but you'd only know that by reading the entire doc. Based on the number of real-world examples I've seen of people memoizing simple lookups, I don't think many people are getting all the way to the bottom. 

Could the docs be updated so that the examples follow best-practices? (I'm happy to open a PR if that's helpful.) Thanks!!

**Comment by evandavis** [comment]
sorry, dupe of #598

**Comment by markerikson** [comment]
Yeah, the Reselect README could definitely use some love, especially with v5 upcoming.

**Comment by aryaemami59** [comment]
> Yeah, the Reselect README could definitely use some love, especially with v5 upcoming.

I'm on it. It's certainly going to look different...
