### ISSUE TITLE
Documentation ignores links in the table of contents entries

### ISSUE THREAD

**Issue by shepmaster** [reduxjs/reselect#663]
On the [FAQ](https://reselect.js.org/faq/), the right-hand TOC has a number of elements missing words:

> [Can I use Reselect without ?](https://reselect.js.org/faq/#can-i-use-reselect-without-)

> [How can I make pre-typed version of for my root state?](https://reselect.js.org/faq/#how-can-i-make-pre-typed-version-of--for-my-root-state)

> [What if I want to use without memoization?](https://reselect.js.org/faq/#what-if-i-want-to-use--without-memoization)

Those all appear to be links in the original headers.

**Comment by aryaemami59** [comment]
I appreciate you opening an issue, I'm going to fix it ASAP.
