### ISSUE TITLE
Incorrect weakMapMemoize alternative example using useCallback

### ISSUE THREAD

**Issue by benax-se** [reduxjs/reselect#682]
The example of avoiding redundant selector calls by using useCallback on the [weakMapMemoize page](https://reselect.js.org/api/weakMapMemoize) is non-working
We still have the same instance of selector, so the cache will share to all the component instances using the same selector

https://codesandbox.io/p/sandbox/reselect-usecallback-demo-y8wldt

**Comment by EskiMojo14** [comment]
yep, agreed - a PR to remove the example (or replace it with a version that works) would be welcome :)
