### ISSUE TITLE
Library do not work in Safari < 14.1

### ISSUE THREAD

**Issue by veksa** [reduxjs/reselect#694]
Error in console when including the library:

`Unexpected token '=' . Expected an opening '(' before a method's parameter list`

The same problem is described here: https://github.com/chakra-ui/chakra-ui/issues/6828

Setting the target to `es2019` in the esm build will fix the problem for High Sierra to Catalina.

PR: https://github.com/reduxjs/reselect/pull/695

**Comment by markerikson** [comment]
We specifically target ES2020 out of the box for the release.

If you need to use older browsers, either transpile the default "modern" build artifact yourself, or use the "legacy" artifact already included in the package (which targets ES2017).
