### ISSUE TITLE
Question: should OutputSelector be used as an InputSelector?

### ISSUE THREAD

**Issue by cchaonie** [reduxjs/reselect#702]
Hi, thanks for the amazing work.
After upgrading to v5, I encountered an issue with the development check.

An OutputSelector will contain a ResultFunction which will do a transformation of the data.

```javascript
const state = { a : 1, b : 2, c : 3 };

const selectA = state => state.a;
const selectB = state => state.b;
const selectC = state => state.c;

const selectAB = createSelector(selectA, selectB, (a, b) => ({a, b})); // transformation, always returns a different reference.

const selectABC1 = createSelector(selectA, selectB, selectAB, (a, b, c) => ({a, b, c}));
const selectABC2 = createSelector(selectA, selectB, (a, b) => ({a, b, c: { a, b }}));
```

Which one is the correct usage, `selectABC1` or `selectABC2`?

**Comment by markerikson** [comment]
I'm not sure I understand the question. Both of those appear to be valid selector definitions. Can you clarify the question?

**Comment by cchaonie** [comment]
@markerikson @aryaemami59 Really appreciate your answers. @aryaemami59 's answer is the one I needed exactly.
