### ISSUE TITLE
Incorrect return type from createSelector when selector returns union of types with keys in common and undefined

### ISSUE THREAD

**Issue by oloftus** [reduxjs/reselect#723]
First off, thanks for the reduxjs project!

Here is a description of what I think is a bug.

See [this repro for a reproduction](https://github.com/oloftus/reselect-repro/blob/main/src/index.tsx). Reproduced with reselect@5.1.1.

### NOK
When a selector returns a type `A | B | undefined`, and types `A` and `B` have a key in common, the return type of the selector is `A | undefined` instead of `A | B or undefined`.

### OK
When types `A` and `B` do not have a key in common, the return type is correct, i.e. `A | B | undefined`.

### OK
When types `A` and `B` have a key in common, but the return union type does not include `undefined`, the return type is correct, i.e. `A | B`.

**Comment by EskiMojo14** [comment]
![image](https://github.com/reduxjs/reselect/assets/18308300/70b17010-4289-4424-9748-71d602a036b9)
this is normal TS behaviour - B is a subtype of A (any B is assignable to A), so TS simplifies to the widest type.

**Comment by oloftus** [comment]
Thanks for the swift response. You're quite right. I hadn't even considered it might be coming from TS and that it is normal behaviour.
